window.MOCK = {
  id: "learn_macro",
  subject: "Macroeconomics",
  title: "Macro — Full Course Learning Sweep",
  blurb: "Built to teach, not test — and graph-complete: one instant-feedback check for every concept node across all 4 modules (M1 Foundations · M2 Money & Monetary Policy · M3 Open Economy · M4 Fiscal & Growth), then 6 written prompts with actionable advice. One pass = the entire syllabus.",
  items: [
    // ===================== M1 · FOUNDATIONS & NATIONAL ACCOUNTS =====================
    {type:"mcq", tag:"M1 · micro vs macro", t:"Macroeconomics studies the economy by:",
     o:["Looking at one firm","Aggregating millions of micro decisions via markets, over space and time","Only fiscal policy","Government accounting"], c:1, why:"Macro = micro choices summed. The framing tells you which lever (demand/supply) is moving."},
    {type:"mcq", tag:"M1 · price–quantity pairs", t:"Macro variables come in price–quantity pairs. The 'price' paired with the money supply is:",
     o:["Inflation","The interest rate (price of money)","The exchange rate","The wage rate"], c:1, why:"Interest↔money supply; inflation↔GDP; exchange rate↔trade balance; wage↔unemployment."},
    {type:"mcq", tag:"M1 · real vs nominal", t:"Nominal GDP up 12%, real GDP up 5%. The ~7% gap is:",
     o:["Population","Inflation (the GDP deflator)","Exports","Error"], c:1, why:"Nominal − Real ≈ inflation. Strip prices to see real output."},
    {type:"mcq", tag:"M1 · short vs long run", t:"Short-run fluctuations are ___-driven; the long-run trend is ___-driven.",
     o:["supply; demand","demand; supply","tax; trade","import; export"], c:1, why:"Short-run output is demand-driven (the choppy 'Sunday vs Monday'); the long-run trend is supply/capacity."},
    {type:"mcq", tag:"M1 · shocks", t:"Which is a SUPPLY shock (not a demand or policy shock)?",
     o:["A surge in consumer confidence","A spike in global oil prices","A cut in the repo rate","A rise in government spending"], c:1, why:"Oil/monsoon hit costs/capacity = supply shocks; confidence = demand; rate/spending = policy shocks."},
    {type:"mcq", tag:"M1 · frictions", t:"A menu that doesn't reprice daily despite cost swings is:",
     o:["Hyperinflation","Price stickiness (menu costs) — a friction","QE","Crowding out"], c:1, why:"Frictions (sticky prices, info gaps, credit constraints) let demand shocks move real output short-run."},
    {type:"mcq", tag:"M1 · circular flow / 3 approaches", t:"The output, income and expenditure approaches to GDP should:",
     o:["Differ widely","All equal the same GDP — one's spending is another's income","Apply only to closed economies","Be averaged randomly"], c:1, why:"Circular flow: every rupee spent is earned, so the three measures reconcile."},
    {type:"mcq", tag:"M1 · GDP identity", t:"C=60, I=20, G=15, NX=5. GDP (Y)?",
     o:["₹90","₹100","₹95","₹110"], c:1, why:"Y = C+I+G+NX = 100."},
    {type:"mcq", tag:"M1 · savings = investment", t:"Private savings 800, Public −200, Foreign 100. Investment?",
     o:["₹600","₹700","₹1,100","₹900"], c:1, why:"S_priv+S_pub+S_for = I = 700. A current-account deficit (foreign savings) helps fund investment."},
    {type:"mcq", tag:"M1 · shares & per-capita", t:"Per-capita GDP (GDP ÷ population) is used to proxy:",
     o:["Total economy size","Average living standards / productivity","Inflation","The trade balance"], c:1, why:"Per-capita strips out population to compare living standards; in India the largest GDP component is Consumption (C)."},
    // ===================== M2 · MONEY, BANKING & MONETARY POLICY =====================
    {type:"mcq", tag:"M2 · functions of money", t:"The three functions of money are medium of exchange, unit of account and:",
     o:["Store of value","Source of inflation","Means of taxation","Foreign reserve"], c:0, why:"Medium of exchange (trade), unit of account (pricing), store of value (save for later)."},
    {type:"mcq", tag:"M2 · money is debt", t:"Modern money is fundamentally:",
     o:["Backed by gold","Fiat — an IOU backed by trust (central-bank vs commercial-bank money)","Backed by reserves only","Created by UPI"], c:1, why:"Cash = central-bank IOU; deposits = commercial-bank IOU. The RBI's real asset is credibility."},
    {type:"mcq", tag:"M2 · aggregates", t:"Which aggregate includes fixed deposits?",
     o:["M0","M1","M3","None"], c:2, why:"M0 base; M1 currency + demand deposits (spend now); M3 adds time deposits/FDs (broad)."},
    {type:"mcq", tag:"M2 · inside/outside · banks create money", t:"Most money (~95%) is created when:",
     o:["The RBI prints cash","Commercial banks lend — loans create deposits (inside money)","Gold is mined","Foreigners invest"], c:1, why:"Outside money (cash) ~5%; inside money (deposits) ~95%, created by bank lending."},
    {type:"mcq", tag:"M2 · money multiplier", t:"CRR = 4%, base ₹500cr. Max deposits? (Deposits = Base ÷ CRR)",
     o:["₹2,000cr","₹12,500cr","₹5,000cr","₹20,000cr"], c:1, why:"1/0.04 = 25 → 500 × 25 = ₹12,500cr."},
    {type:"mcq", tag:"M2 · govt bonds", t:"For a government bond (G-Sec), which is FIXED at issue?",
     o:["The market price","The coupon and the face value repaid at maturity","The yield","The demand"], c:1, why:"Coupon and face value are fixed; price and yield move in the secondary market."},
    {type:"mcq", tag:"M2 · bond yield", t:"A ₹1,000 G-Sec, 8% coupon, trades at ₹800. Yield?",
     o:["8%","10%","12.5%","6.4%"], c:1, why:"80/800 = 10%. Price down → yield up (inverse)."},
    {type:"mcq", tag:"M2 · interest = price of money", t:"The interest rate is best understood as:",
     o:["A tax","The price of money over time (the cost of borrowing / reward for saving)","The inflation rate","The exchange rate"], c:1, why:"Rates allocate money across time — high rates make 'money now' expensive."},
    {type:"mcq", tag:"M2 · repo / arbitrage", t:"A repo hike lifts G-Sec and loan rates because:",
     o:["The RBI sets all rates by law","Arbitrage links them — like connected water tanks","Banks must copy it","It only affects overnight rates"], c:1, why:"The repo anchors the overnight rate; arbitrage transmits it up the curve to EMIs."},
    {type:"mcq", tag:"M2 · CPI vs WPI", t:"The RBI's legal target is based on:",
     o:["WPI wholesale","CPI retail — headline 4% ±2% (watching core ex food & fuel)","Core only","The deflator"], c:1, why:"CPI is what households feel; core strips volatile food/fuel for the underlying trend."},
    {type:"mcq", tag:"M2 · demand vs cost-push", t:"A monsoon failure spikes food prices. This inflation is:",
     o:["Demand-pull","Cost-push (supply shock) — rate hikes can't fix it","Hyperinflation","Core"], c:1, why:"AS shifts left; hiking only crushes demand while prices stay high → stagflation."},
    {type:"mcq", tag:"M2 · expectations", t:"Why anchor inflation expectations?",
     o:["They're irrelevant","Un-anchored expectations are self-fulfilling (wage-price spiral)","They only affect exports","They don't"], c:1, why:"If people expect inflation, they demand higher wages/prices, creating it."},
    {type:"mcq", tag:"M2 · inflation targeting", t:"Under flexible inflation targeting, if the RBI misses the band for 3 consecutive quarters it must:",
     o:["Resign","Give a formal explanation to the government","Raise the CRR","Devalue"], c:1, why:"The legal target (CPI 4% ±2%) makes the RBI accountable, not omnipotent."},
    {type:"mcq", tag:"M2 · output gap", t:"Actual GDP below Potential signals:",
     o:["Overheating → hike","Slack/unemployment → ease","Hyperinflation","A surplus"], c:1, why:"Gap = Actual − Potential. Negative → stimulate; positive → tighten."},
    {type:"mcq", tag:"M2 · dual mandate / trade-off", t:"The RBI's dual mandate forces a short-run trade-off between:",
     o:["Exports and imports","Controlling inflation and supporting output/employment","Taxes and spending","FDI and FPI"], c:1, why:"Easing boosts output but risks inflation; the output gap guides the balance."},
    {type:"mcq", tag:"M2 · transmission channels", t:"Which is NOT a monetary transmission channel?",
     o:["Interest rate","Asset price (wealth effect)","Expectations","Exchange-control"], c:3, why:"Five channels: interest rate, credit, asset price, balance sheet, expectations."},
    {type:"mcq", tag:"M2 · investment sensitivity", t:"A firm invests in a project when:",
     o:["The CRR rises","Its expected return exceeds the cost of borrowing","Inflation is high","The rupee depreciates"], c:1, why:"Investment is interest-rate-sensitive: higher rates raise the hurdle, cutting I."},
    {type:"mcq", tag:"M2 · limits / ZLB", t:"At ~0% rates in a deep slump, the next tool is:",
     o:["Raise CRR","Quantitative Easing — buy assets to inject liquidity","Devalue","Nothing"], c:1, why:"At the Zero Lower Bound conventional cuts die → QE. (Supply shocks also disable rate policy.)"},
    {type:"mcq", tag:"M2 · yield curve", t:"The yield curve plots:",
     o:["Inflation over time","Yields against maturity — the 'family of rates' / term structure","GDP against years","Exchange rates"], c:1, why:"It shows how rates vary by tenor; an inverted curve often signals a slowdown."},
    {type:"mcq", tag:"M2 · CRR / SLR / CAR", t:"Match the bank ratio to its meaning:",
     o:["CRR = capital buffer","CRR = cash with RBI; SLR = liquid govt securities held; CAR = capital-adequacy buffer","SLR = cash with RBI","All identical"], c:1, why:"CRR & SLR are liquidity tools; CAR is a solvency buffer of the bank's own capital."},
    {type:"mcq", tag:"M2 · Fisher", t:"Loan 7%, inflation 7%. Real cost?",
     o:["14%","0% — essentially free","7%","−7%"], c:1, why:"Real = nominal − inflation. Convert to real before judging tight vs loose."},
    {type:"mcq", tag:"M2 · liquidity toolkit (OMO)", t:"To inject liquidity, the RBI conducts an Open Market Operation by:",
     o:["Selling bonds to banks","Buying bonds from banks (paying cash into the system)","Raising the CRR","Raising the SLR"], c:1, why:"OMO buy = cash in, liquidity up. The toolkit: repo ops, OMO, CRR/SLR, forward guidance."},
    {type:"mcq", tag:"M2 · NPAs / NBFCs", t:"The risk from NBFCs (shadow banks) is:",
     o:["They print money","Contagion — they borrow short and lend long outside full banking regulation, so stress spreads (e.g. IL&FS)","They set the repo rate","They issue currency"], c:1, why:"Lightly-regulated maturity mismatch makes NBFC failures spill into the financial system."},
    // ===================== M3 · OPEN ECONOMY, TRADE & FOREX =====================
    {type:"mcq", tag:"M3 · open-economy NX", t:"Exports 50, Imports 70. Net exports (NX) and its effect on Y?",
     o:["+20, adds to GDP","−20, a trade deficit that drags on GDP","+120","−120"], c:1, why:"NX = X − M = −20. In Y = C+I+G+NX, a deficit subtracts."},
    {type:"mcq", tag:"M3 · exchange rate (asset mkt)", t:"E = ₹ per $1 rises from 80 to 84. This means:",
     o:["Rupee appreciated","Rupee depreciated (more ₹ per $); exports cheaper, imports dearer","Dollar weakened","No change"], c:1, why:"E↑ ⇒ $ appreciates, ₹ depreciates; the rupee 'price' = 1/E falls."},
    {type:"mcq", tag:"M3 · IRP (UIP)", t:"India 7%, US 3%. By UIP the rupee is expected to:",
     o:["Appreciate ~4%","Depreciate ~4% (no-arbitrage)","Stay flat","Depreciate 10%"], c:1, why:"%Δ₹ ≈ i_IND − i_US = 4% expected depreciation; covered IRP locks it via the forward rate."},
    {type:"mcq", tag:"M3 · PPP", t:"Real exchange rate e = E×(P_for/P_dom) = 1.25. The rupee is:",
     o:["Overvalued","Undervalued — India cheap → appreciation pull toward e=1","Pegged","About to be devalued"], c:1, why:"PPP: e → 1 long-run (Big Mac Index). e>1 → buyers flock to cheap India."},
    {type:"mcq", tag:"M3 · impossible trinity", t:"A country can have at most TWO of:",
     o:["Low inflation, growth, low unemployment","Fixed exchange rate, free capital mobility, independent monetary policy","Surplus, low debt, low tax","FDI, FPI, reserves"], c:1, why:"India picks monetary independence + capital mobility, sacrificing a fixed rate."},
    {type:"mcq", tag:"M3 · regimes", t:"India's exchange-rate regime is:",
     o:["A hard USD peg","A pure free float","A managed float — market-driven, RBI smooths volatility","A currency board"], c:2, why:"The trilemma 'middle ground': float + intervention to smooth swings."},
    {type:"mcq", tag:"M3 · exchange-rate channel", t:"A repo HIKE affects inflation through the exchange rate by:",
     o:["↑i → capital inflow → ₹ appreciates → imports cheaper → inflation↓","Weakening the rupee","Raising exports","No effect"], c:0, why:"Higher rates attract inflows → rupee appreciates → cheaper imports, weaker NX → AD & inflation down."},
    {type:"mcq", tag:"M3 · BOP", t:"Current Account + Capital Account = 0 means a current-account deficit is:",
     o:["Illegal","Financed by a capital-account surplus (foreign inflows)","Impossible","Funded by printing"], c:1, why:"A CAD must be financed by net foreign capital inflows."},
    {type:"mcq", tag:"M3 · external vulnerability / 1991", t:"The 1991 crisis was triggered by:",
     o:["A stock crash","Deficits funded by hot money + the Gulf War shock draining reserves to ~2 weeks of imports","Hyperinflation","A bank fraud"], c:1, why:"Fragile financing met an external shock → ~47 tonnes of gold pledged → reforms."},
    {type:"mcq", tag:"M3 · history of regimes", t:"The correct historical order of global currency regimes is:",
     o:["Fiat → gold → Bretton Woods","Gold standard → Bretton Woods → fiat (floating)","Bretton Woods → gold → fiat","Fiat → Bretton Woods → gold"], c:1, why:"Gold standard → Bretton Woods (USD pegged to gold) → fiat floating after 1971."},
    {type:"mcq", tag:"M3 · regime choice", t:"A fixed exchange rate is most useful when a country mainly faces:",
     o:["Real shocks","Nominal/monetary shocks (a peg imports stability)","No shocks","Supply shocks only"], c:1, why:"Pegs cushion nominal shocks; against real shocks a float lets the currency adjust."},
    {type:"mcq", tag:"M3 · sterilized intervention", t:"'Sterilized intervention' means the RBI:",
     o:["Lets the rupee float freely","Buys/sells FX to manage the rupee, then offsets the money-supply effect via OMO","Raises the CRR only","Bans capital flows"], c:1, why:"It manages the rupee without disturbing domestic liquidity — important given India's risk premium."},
    {type:"mcq", tag:"M3 · trade policy", t:"A tariff is a trade-policy instrument that:",
     o:["Subsidises imports","Taxes imports to protect domestic producers (India has shifted toward liberalisation)","Bans exports","Fixes the exchange rate"], c:1, why:"Tariffs/quotas protect domestic industry; India liberalised progressively post-1991."},
    // ===================== M4 · FISCAL POLICY & GROWTH =====================
    {type:"mcq", tag:"M4 · fiscal policy", t:"Fiscal policy is the government's use of:",
     o:["Interest rates and the CRR","Spending and taxation to influence demand","The exchange rate","Bank regulation"], c:1, why:"Fiscal = G and T (vs monetary = rates/money). Expansionary = ↑G or ↓T."},
    {type:"mcq", tag:"M4 · revenue & spending", t:"Which is a CAPITAL (not revenue) expenditure for the government?",
     o:["Salaries and interest payments","Building a new highway or port (asset creation)","Subsidies","Pensions"], c:1, why:"Capex creates assets (growth-enhancing); revenue spending (salaries, subsidies) is recurring."},
    {type:"mcq", tag:"M4 · debt sustainability", t:"Government debt/GDP stabilises when:",
     o:["r > g","Growth g > interest rate r","The deficit is zero","Inflation is zero"], c:1, why:"If g > r the economy outgrows its interest bill (sustainable); r > g spirals."},
    {type:"mcq", tag:"M4 · crowding out", t:"Heavy government borrowing can crowd out private investment by:",
     o:["Banning private loans","Pushing up interest rates, making private borrowing costlier","Lowering rates","Boosting exports"], c:1, why:"Public borrowing competes for savings → rates rise → private investment displaced."},
    {type:"mcq", tag:"M4 · fiscal multiplier", t:"MPC = 0.8, govt spends ₹100cr. Total GDP impact? (Mult = 1/(1−MPC))",
     o:["₹100cr","₹400cr","₹500cr","₹800cr"], c:2, why:"1/0.2 = 5 → ₹500cr. Each rupee is re-spent at rate MPC (Keynes)."},
    {type:"mcq", tag:"M4 · fiscal vs monetary", t:"When monetary transmission is broken (credit jammed / ZLB), the better tool is:",
     o:["More rate cuts","Fiscal stimulus that injects demand directly (bypassing banks)","Raising the CRR","Tightening"], c:1, why:"Fiscal doesn't need banks to lend; the two are complements used countercyclically."},
    {type:"mcq", tag:"M4 · growth theory", t:"Capital accumulation alone cannot sustain growth because of:",
     o:["Inflation","Diminishing returns to capital (the Malthusian trap)","Trade deficits","Taxes"], c:1, why:"Each extra unit of capital adds less; you can't grow forever by just adding machines."},
    {type:"mcq", tag:"M4 · technology engine", t:"Sustained long-run per-capita growth comes mainly from:",
     o:["More workers","Technology / productivity (shifts the frontier out)","More land","Higher prices"], c:1, why:"Technology escapes diminishing returns — the true long-run growth engine."},
    {type:"mcq", tag:"M4 · macro myths", t:"Which is a macro MYTH (false)?",
     o:["A trade deficit always means the economy is failing","Long-run growth comes from productivity","Money is mostly bank deposits","Supply shocks blunt monetary policy"], c:0, why:"A CAD can simply reflect strong investment financed by foreign savings — not failure."},
    {type:"mcq", tag:"M4 · Keynes", t:"Keynes' core fiscal insight was that in a slump:",
     o:["Governments should always balance the budget","Government spending can lift demand when private demand collapses","Only the central bank matters","Deficits are always harmful"], c:1, why:"Active fiscal policy fills the demand gap when households/firms won't spend."},
    {type:"mcq", tag:"M4 · FRBM / fiscal space", t:"The FRBM Act exists to:",
     o:["Set the inflation target","Cap deficits and preserve 'fiscal space' to act in downturns","Manage reserves","Set bank capital"], c:1, why:"Discipline in good times keeps room to spend countercyclically in bad times."},
    {type:"mcq", tag:"M4 · countercyclical", t:"Countercyclical fiscal strategy means:",
     o:["Spend more in booms","Stimulate in slumps, consolidate in booms — never pro-cyclical","Always balance the budget","Never intervene"], c:1, why:"Lean against the cycle; spending in booms overheats and wastes fiscal space."},
    // ===================== WRITTEN (actionable advice + examples) =====================
    {type:"written", t:"Explain the difference between <b>nominal and real GDP</b>, and why it matters when reading growth figures.",
     looking:["Nominal = current prices (inflation-contaminated)","Real = constant base-year prices (isolates quantity)","Nominal − Real ≈ inflation (deflator)","High nominal growth can be mostly price rises — real GDP is the honest measure"],
     model:"Nominal GDP values output at today's prices, so it rises both when we produce more AND when prices climb. Real GDP fixes prices at a base year, stripping inflation to reveal the true change in quantity. The gap between nominal and real growth is essentially inflation (the GDP deflator). It matters because '12% growth' can be mostly inflation — if prices rose 8%, real output only grew ~4%. Use real GDP to judge genuine improvement in output and living standards.",
     use:"Any growth/comparison question — strip inflation first; also cross-country comparisons (use real, PPP-adjusted)."},
    {type:"written", t:"A failed monsoon spikes food inflation; a commentator demands an immediate RBI rate hike. Evaluate using <b>demand-pull vs cost-push</b>.",
     looking:["Identify cost-push / supply shock (AS shifts left)","Monetary policy acts on demand (cools C and I)","Rate hikes can't grow food — only suppress demand → stagflation risk","Food shocks often reverse with the next harvest","Act only if expectations un-anchor or it feeds core"],
     model:"This is cost-push inflation: a supply shock raises prices for cost reasons, not excess demand. Monetary policy works on the demand side, so a hike cools consumption and investment but can't grow more food — it would suppress adequate demand and hurt output, risking stagflation. Food shocks are usually transitory and reverse with the next harvest, so the textbook response is to look through them, hiking only if the shock threatens to un-anchor inflation expectations or spill into core inflation.",
     use:"Any 'should the RBI hike?' scenario: classify the shock first. Demand-pull → tighten; cost-push → near-powerless, look through it."},
    {type:"written", t:"The RBI hikes the repo rate 50 bps. <b>Trace</b> the effect on household consumption and name a channel that may fail.",
     looking:["Repo up → bank funding cost up → yields/lending rates/EMIs up (arbitrage)","Higher EMIs cut disposable income → C falls → AD & inflation ease (lags)","Reinforcing: asset-price/wealth effect, expectations, exchange-rate channel","Failing channel: credit channel if banks don't pass it through"],
     model:"A repo hike raises banks' cost of funds; via arbitrage this lifts G-Sec yields and lending rates, pushing up EMIs. Higher EMIs cut disposable income and deter car/home borrowing → consumption falls → AD and inflation ease, with lags. The asset-price channel (softer stocks/property → negative wealth effect), the expectations channel, and the exchange-rate channel (inflows → stronger rupee → cheaper imports) reinforce it. The credit channel may fail: if banks are risk-averse or transmission is sticky, rates don't pass through and the policy underperforms.",
     use:"The template for any 'trace the policy' question — mechanism → reinforcing channels → failure point + lags."},
    {type:"written", t:"The US sharply raises rates while India holds. Walk through the effect on the <b>rupee</b> and India's options.",
     looking:["IRP: rate gap favours US → capital flight from India","Excess rupee supply → depreciation","Knock-on: imported inflation, CAD pressure","RBI options: hike to narrow gap; sell USD reserves; sterilized intervention","Trade-offs framed by the trilemma"],
     model:"Higher US rates widen the differential, so by Interest Rate Parity capital flows out of India chasing US yields. This excess supply of rupees depreciates the currency, importing inflation (costlier oil/imports) and pressuring the current account. India's options reflect the trilemma: hike rates to stem outflows (but that hurts growth), sell USD reserves to smooth the fall under its managed float — often via sterilized intervention to protect domestic liquidity (but that burns the buffer), or accept some depreciation (which aids exports). In practice the RBI blends measured intervention with rate signals.",
     use:"Any 'global rates rise / Fed hikes' scenario: IRP → capital flight → depreciation → imported inflation → RBI trade-offs."},
    {type:"written", t:"'A fiscal deficit is always dangerous.' Critically evaluate using <b>debt sustainability (r vs g)</b>.",
     looking:["Reject the absolutism — context decides","Debt/GDP stabilises if g > r; spirals if r > g","Benign: productive deficits (capex) raising future g","Dangerous: funding consumption when r > g, eroding fiscal space","Mention crowding out and FRBM discipline"],
     model:"Too absolute. A deficit's danger depends on r vs g. If growth g exceeds the interest rate r, the economy outgrows its interest bill and debt/GDP drifts down — sustainable, especially if the deficit funds productive capital expenditure that lifts future growth. It turns dangerous when r exceeds g (debt compounds faster than the economy) or when it merely funds recurring consumption and burns the fiscal space needed for crises; large deficits can also crowd out private investment. So deficits are a tool — benign when productive and g > r, dangerous otherwise — which is why FRBM-style discipline and countercyclical use matter.",
     use:"Any deficit/debt question: anchor on r vs g, distinguish capex vs revenue spending, add crowding out + fiscal space."},
    {type:"written", t:"What drives <b>long-run growth</b>, and how does it differ from short-run demand management?",
     looking:["Long run = supply-side: capital, labour, ultimately technology/productivity","Capital alone hits diminishing returns (Malthusian trap)","Short run = demand management (monetary/fiscal smoothing the cycle)","Don't answer a long-run question with demand stimulus","Example: reforms/innovation/human capital raise the trend"],
     model:"Long-run growth is a supply-side story: potential output rises with capital and labour, but sustained per-capita growth ultimately comes from technological progress and productivity, because capital accumulation alone runs into diminishing returns (how economies escape the Malthusian trap). Short-run demand management — monetary and fiscal policy — only smooths fluctuations around that trend; it cannot raise the trend itself. So a recession calls for demand stimulus, but lifting a country's long-run growth needs structural drivers: innovation, human capital, infrastructure and institutions that raise productivity.",
     use:"Distinguish 'how to end a recession' (demand) from 'how to make a nation richer over decades' (supply/technology)."}
  ]
};
