window.MOCK = {
  id: "learn_npd",
  subject: "NPD",
  title: "NPD — Full Course Learning Sweep",
  blurb: "Built to teach, not test — and graph-complete: instant-feedback checks covering every concept across all 8 modules (foundations → launch & public policy), with the case studies folded in as examples, then 6 written prompts with actionable advice. One pass = the entire course.",
  items: [
    // ===================== M1 · FOUNDATIONS & PROCESS =====================
    {type:"mcq", tag:"M1 · why NPD", t:"Why must even a market leader keep doing NPD?",
     o:["To spend R&D budget","Rivals catch up and erode advantage — you renew it or commoditise","Regulation","To keep designers busy"], c:1, why:"NPD renews competitive advantage; complacency killed Kodak and Nokia."},
    {type:"mcq", tag:"M1 · categories of new", t:"Aspirin moving from painkiller to heart-health is which 'new' category?",
     o:["New-to-world","Line extension","Repositioning","Cost reduction"], c:2, why:"Same product, new use/segment. The 6 types run new-to-world → new line → extension → improvement → reposition → cost-reduction."},
    {type:"mcq", tag:"M1 · three levels of innovation", t:"Innovation novelty ranges across three levels — lowest to highest:",
     o:["Radical → really-new → incremental","Incremental → really-new (dynamically continuous) → radical (discontinuous)","Cheap → mid → premium","Local → national → global"], c:1, why:"Incremental tweaks → really-new → radical/breakthrough; risk and reward rise with novelty."},
    {type:"mcq", tag:"M1 · PM role", t:"The Product Manager in NPD should act as:",
     o:["A narrow specialist","A General Manager bridging Marketing, Operations and Finance (a multidisciplinary role)","Only a marketer","A salesperson"], c:1, why:"NPD is multidisciplinary; products die in the gap between 'cool design' and 'unviable cost' — the PM closes it."},
    {type:"mcq", tag:"M1 · product vs user-centric", t:"Bottle Loft hyped its magnet as 'Strong Like a Bull' and flopped because:",
     o:["Magnets are bad","It sold a product feature while ignoring the user's real fear — the adhesive failing","Ads never work","Price too high"], c:1, why:"Be user-centric: solve the user's whole anxiety, not the engineering feat you're proud of."},
    {type:"mcq", tag:"M1 · business model / why models fail", t:"Uber's model shows business models fail when:",
     o:["They have a logo","Any one pillar (value creation, delivery or capture) is broken — e.g. great demand but no path to profit","They use an app","They scale"], c:1, why:"A model must create, deliver AND capture value; burning cash with no capture mechanism is a broken model."},
    {type:"mcq", tag:"M1 · NPD process", t:"The canonical NPD process runs:",
     o:["Launch → idea → test","PIC → idea generation → concept testing → prototyping → use-testing → market testing → launch","Idea → launch → design","Test → idea → build"], c:1, why:"A disciplined funnel from charter to launch — each stage a gate that kills weak ideas cheaply."},
    {type:"mcq", tag:"M1 · PIC / mission", t:"A Product Innovation Charter (PIC) and product mission statement primarily:",
     o:["Are the final spec","Align cross-functional teams on scope, target market, timeline and goals BEFORE development","Test willingness to pay","Replace the business case"], c:1, why:"The PIC is the strategic 'north star' set before the funnel begins — not a spec sheet."},
    {type:"mcq", tag:"M1 · portfolio", t:"A balanced new-product portfolio (mapped on a 2-D risk-reward grid) means:",
     o:["All breakthrough bets","Balancing high-risk breakthroughs with safer derivatives/extensions across the map","All safe tweaks","One big project"], c:1, why:"Don't crowd every project into one cell — spread risk/reward so steady wins fund the moonshots."},
    {type:"mcq", tag:"M1 · funnel & stage gates", t:"Stage gates exist to:",
     o:["Slow teams down","Apply Go/No-Go checks (narrative + numbers) so weak ideas are killed before spend escalates","Add paperwork","Pick the colour"], c:1, why:"Each gate needs both a narrative (who pays, why?) and numbers (does it profit?) approval."},
    {type:"mcq", tag:"M1 · flexibility & metrics", t:"'Flexibility' in product development and good development metrics together let a firm:",
     o:["Ignore deadlines","Delay commitment on uncertain specs and track funnel health (e.g. cycle time, gate conversion) to decide faster","Skip testing","Avoid planning"], c:1, why:"Keep options open where uncertainty is high; measure the funnel to manage it, not just to report."},
    // ===================== M2 · IDEAS, RESEARCH & CONCEPT TESTING =====================
    {type:"mcq", tag:"M2 · identifying opportunities", t:"Lego's revival (from fixed sets to a modular brick system) shows opportunities come from:",
     o:["Copying rivals","Re-reading customer needs and reframing the product around them (modularity + creativity)","Cutting price only","More advertising"], c:1, why:"Opportunity-spotting means reframing around unmet needs — Lego rebuilt value around open-ended play."},
    {type:"mcq", tag:"M2 · Buyer Utility Map", t:"The Buyer Utility Map scans utility across:",
     o:["Price vs cost","The six experience stages: purchase, delivery, use, supplements, maintenance, disposal","Competitors only","Funnel stages"], c:1, why:"Untapped utility often hides in stages rivals ignore (disposal, maintenance)."},
    {type:"mcq", tag:"M2 · frustrations as source", t:"A rich, cheap source of new-product ideas is:",
     o:["Stock prices","Customer frustrations / pain points (anger signals an unmet need)","Competitor logos","Random brainstorms"], c:1, why:"Frustration is a market signal — solve the pain people already complain about."},
    {type:"mcq", tag:"M2 · lead users", t:"Lead users — and the limitation of studying them — are:",
     o:["Average buyers; no limits","At the market's leading edge / analogous markets / extreme users; limitation = their solutions can be too niche to generalise","Laggards; cheap","Only competitors; risky"], c:1, why:"They face tomorrow's needs today, but their fixes may not scale to the mass market."},
    {type:"mcq", tag:"M2 · Morville honeycomb", t:"Morville's UX honeycomb says a great experience must be useful, usable, desirable, findable, accessible, credible and:",
     o:["Cheap","Valuable","Modular","Patented"], c:1, why:"The seventh facet is valuable — it must deliver value to the business too."},
    {type:"mcq", tag:"M2 · market research", t:"Market research for new products is hardest because:",
     o:["It's illegal","Customers can't reliably evaluate products that don't yet exist (stated intent is unreliable)","It's free","It always works"], c:1, why:"This is why behaviour-based tests beat 'would you buy?' surveys — people can't imagine the unfamiliar well."},
    {type:"mcq", tag:"M2 · Kano", t:"Brakes: absent → fury, present → neutral. Kano category?",
     o:["Delighter","One-dimensional","Must-be","Indifferent"], c:2, why:"Must-be: secure all of these first; then compete on one-dimensionals; differentiate with delighters."},
    {type:"mcq", tag:"M2 · Product Variety Matrix", t:"A Product Variety Matrix helps a firm decide:",
     o:["The ad budget","How much product variety to offer vs the cost/complexity of providing it","The CEO's pay","The launch date"], c:1, why:"More variety pleases segments but raises cost/complexity — the matrix balances the trade-off."},
    {type:"mcq", tag:"M2 · QFD / House of Quality", t:"In QFD's House of Quality, the 'roof' shows:",
     o:["Customer importance","Correlations among technical requirements — conflicts and synergies","Competitor prices","Forecasts"], c:1, why:"WHATs (needs) map to HOWs (specs) via 9/3/1; the roof flags spec-vs-spec tensions (lighter vs stronger)."},
    {type:"mcq", tag:"M2 · QFD weighting", t:"A spec scores 9 with a need rated 4 and 3 with a need rated 5. Technical weight?",
     o:["36","51","45","27"], c:1, why:"(4×9)+(5×3) = 36+15 = 51. Higher weight → prioritise that spec."},
    {type:"mcq", tag:"M2 · user toolkits", t:"A 'user toolkit' for innovation lets:",
     o:["Engineers work alone","Customers design/configure their own solution within set bounds (shifting design to those who know the need)","Marketing set price","The CEO decide"], c:1, why:"Effective toolkits give users a sandbox + library + instant feedback so they co-create the product."},
    {type:"mcq", tag:"M2 · evaluation / Risk-Payoff", t:"A Risk-Payoff matrix and concept-evaluation dimensions are used to:",
     o:["Set salaries","Rank concepts by reward vs risk and screen them on agreed criteria before spending","Design the logo","Pick the office"], c:1, why:"Evaluation gates rank and filter ideas so capital flows to the best risk-adjusted bets."},
    {type:"mcq", tag:"M2 · concept testing", t:"78% 'would buy' in a survey but real trial is 12%. Lesson:",
     o:["Survey too small","Stated-intent overstates behaviour (hypothetical bias); behaviour-based tests predict better","Wrong price","Beta would fix it"], c:1, why:"Never make a launch call on stated intent — use a simulated/real test market."},
    {type:"mcq", tag:"M2 · conjoint", t:"Conjoint analysis is used to:",
     o:["Test durability","Decompose preferences into per-attribute part-worths, revealing trade-offs","Forecast share price","Design the factory"], c:1, why:"It shows how much each attribute really contributes — how you price features and pick configurations."},
    {type:"mcq", tag:"M2 · ATAR", t:"Market 2M, Awareness 50%, Trial 40%, Availability 80%, Repeat 50%. Demand?",
     o:["80,000","160,000","320,000","400,000"], c:1, why:"Multiply the fractions: 2M × 0.5 × 0.4 × 0.8 × 0.5 = 160,000. The weakest fraction caps demand."},
    {type:"mcq", tag:"M2 · product protocol", t:"A 'product protocol' is:",
     o:["A legal contract","An agreed statement of what the product must be/do — aligning marketing and R&D before development","A test plan","A price list"], c:1, why:"The protocol is the handshake between the market need and the technical spec, reducing late surprises."},
    {type:"mcq", tag:"M2 · financial analysis", t:"Financial/managerial analysis at the business-case gate (e.g. Rubbermaid, Chipotle) checks:",
     o:["The colour palette","Whether the numbers work — payback, NPV/IRR, margins — at a price customers accept","Employee morale","The font"], c:1, why:"The Numbers Test: a compelling story still dies if it can't be produced profitably."},
    // ===================== M3 · DESIGN, PROTOTYPING, TEAMS & SERVICES =====================
    {type:"mcq", tag:"M3 · design-driven innovation", t:"Design-driven innovation competes primarily on:",
     o:["Lowest price","Meaning and experience (what the product means to users), not just features","Factory size","Ad spend"], c:1, why:"Good design shapes how a product is understood and loved — a durable, hard-to-copy edge."},
    {type:"mcq", tag:"M3 · modular vs integral", t:"An iPhone's tightly interdependent internals are:",
     o:["Modular","Integral","Platform","Open"], c:1, why:"Integral = coupled, optimised whole (top performance, costly to change). Don't reverse with modular (PC, bicycle)."},
    {type:"mcq", tag:"M3 · six modularity", t:"Lego (standard connectors, free configuration) is which modularity type?",
     o:["Bus","Sectional","Cut-to-fit","Component-swapping"], c:1, why:"Sectional. The six: component-swapping, component-sharing, bus, sectional, mix, cut-to-fit."},
    {type:"mcq", tag:"M3 · DFM", t:"Design for Manufacturing (DFM) means:",
     o:["Design the ad","Design so it's cheap and easy to build (fewer parts, easy assembly)","Build before design","Design for the customer"], c:1, why:"A great design that's a nightmare to build dies on cost — DFM is where the 10/100 rule pays off."},
    {type:"mcq", tag:"M3 · Swatch vs Shimano", t:"Swatch (interchangeable style modules) vs Shimano (tightly integrated gears) illustrate:",
     o:["B2B vs B2C","Modular vs integral design choices within an industry","Cheap vs expensive","Old vs new"], c:1, why:"The same industry can split on architecture by whether customers value variety or peak performance."},
    {type:"mcq", tag:"M3 · prototyping", t:"Prototyping (in-house vs vendor — e.g. Gillette Mach3's heavy investment) exists to:",
     o:["Finalise marketing","Turn ideas into testable reality to learn and de-risk before committing to tooling","Replace concept testing","Set the price"], c:1, why:"Choose in-house (control/IP) vs vendor (speed/cost) by the project's risk and secrecy."},
    {type:"mcq", tag:"M3 · org structures", t:"For a radical breakthrough needing speed and integration, the best NPD structure is:",
     o:["Functional","Lightweight matrix","Autonomous / 'tiger' team (dedicated, co-located)","No structure"], c:2, why:"Spectrum: functional → lightweight → heavyweight → autonomous. Match structure to project type."},
    {type:"mcq", tag:"M3 · product integrity", t:"A beautifully engineered product that misreads customers has:",
     o:["High internal, low external integrity","Low internal, high external","Neither","Both"], c:0, why:"Internal = function↔structure coherence; external = product↔customer fit. Great products achieve both."},
    {type:"mcq", tag:"M3 · developing services", t:"Developing new services (and 'platform thinking' for services) differs from goods because services are:",
     o:["Always cheaper","Intangible, perishable and co-produced with the customer — so design the experience and reusable platforms","Never tested","Physical"], c:1, why:"You design the process/experience; platform thinking lets you reuse components across many service variants."},
    {type:"mcq", tag:"M3 · PSS", t:"Rolls-Royce 'Power by the Hour' (pay per hour of thrust) is which PSS type?",
     o:["Product-oriented","Use-oriented","Result-oriented","Asset-sharing"], c:2, why:"Result-oriented: buy the outcome; provider owns/maintains everything and is paid on results."},
    {type:"mcq", tag:"M3 · team leadership", t:"Structuring and 'culturing' an NPD team (ownership, roles, training, virtual teams) matters because:",
     o:["It doesn't","Clear ownership/leadership and the right roles drive integration — the soft side that makes or breaks delivery","Only the PM matters","Tools matter most"], c:1, why:"Heavyweight ownership + co-location + the right roles is what actually ships integrated products."},
    // ===================== M4 · USE-TESTING, DEMAND CREATION & IP =====================
    {type:"mcq", tag:"M4 · use-testing decisions", t:"Key decisions in product-use testing include:",
     o:["The logo","Who tests, where, for how long, and what to measure — escalating realism cheaply","The price only","The ad budget"], c:1, why:"Design the test to answer the readiness question at least cost before scaling up."},
    {type:"mcq", tag:"M4 · alpha & beta", t:"Alpha vs Beta testing — which is right?",
     o:["Alpha external; Beta internal","Alpha = internal/controlled; Beta = real external users in natural conditions","Both external","Both internal"], c:1, why:"Alpha in-house first, Beta out-in-the-world second. Classic reversal trap."},
    {type:"mcq", tag:"M4 · gamma", t:"Gamma testing is:",
     o:["Internal-only","Final verification against specifications before full launch","Live A/B","Lead-user testing"], c:1, why:"Alpha (internal) → Beta (real users) → Gamma (spec conformance), vital in regulated products."},
    {type:"mcq", tag:"M4 · creating demand", t:"'Creating demand without a latent need' (a genuinely new category) requires the firm to:",
     o:["Just lower price","Educate the market and shape the need — riskier and slower than serving existing demand","Copy a rival","Do nothing"], c:1, why:"Building markets for the truly new means demand creation, not just demand capture."},
    {type:"mcq", tag:"M4 · differentiation", t:"Horizontal vs vertical differentiation — which is right?",
     o:["Horizontal = objectively better; Vertical = taste","Horizontal = taste-based (red vs blue); Vertical = objectively better (faster chip)","Identical","Horizontal = services only"], c:1, why:"Vertical → compete on performance; horizontal → segment by taste. Don't reverse."},
    {type:"mcq", tag:"M4 · choosing options (2×2)", t:"A 2×2 for choosing between product options typically trades off:",
     o:["Colour vs size","Two decision dimensions (e.g. attractiveness vs feasibility / fit) to pick where to play","Price vs ad","CEO vs board"], c:1, why:"The 2×2 forces an explicit trade-off so you back the high-fit, high-payoff option."},
    {type:"mcq", tag:"M4 · IP types", t:"Which IP type protects an invention?",
     o:["Trademark","Patent","Copyright","Trade secret"], c:1, why:"Patent = inventions (disclosed, time-limited). Trademark = brand; copyright = creative works; trade secret = know-how."},
    {type:"mcq", tag:"M4 · patent strategy & piracy", t:"Filing a patent trades secrecy for a monopoly; the downside (and why firms fight piracy, e.g. CarryPro) is:",
     o:["Patents are free","Disclosure teaches rivals, and weak enforcement invites copying — so strategy + anti-piracy effort matter","Patents last forever","No downside"], c:1, why:"A patent publishes your invention; without a strategy and enforcement, copycats erode the advantage."},
    // ===================== M5 · BLUE OCEAN, PLAN, EMERGING MARKETS, DESIGN THINKING =====================
    {type:"mcq", tag:"M5 · strategy canvas", t:"A Strategy Canvas plots:",
     o:["Profit over time","The value curve — how you and rivals score on the factors of competition","Org chart","Market share only"], c:1, why:"It visualises where to diverge from the industry curve — the setup for ERRC."},
    {type:"mcq", tag:"M5 · ERRC", t:"Blue Ocean's ERRC pairs cost and value as:",
     o:["Eliminate/Raise cut cost","Eliminate & Reduce cut cost; Raise & Create lift value","All cut cost","All lift value"], c:1, why:"Together they break the value-cost trade-off and open uncontested space."},
    {type:"mcq", tag:"M5 · red vs blue ocean", t:"IPL and the iPhone are cited as ___ examples.",
     o:["Red ocean","Blue ocean — creating new market space rather than fighting on existing terms","Cost-leadership","Line extensions"], c:1, why:"Blue ocean creates new demand from non-customers; red ocean is bloody head-to-head competition."},
    {type:"mcq", tag:"M5 · business plan & consultants", t:"A new-product business plan (sometimes aided by strategy consultants) primarily:",
     o:["Designs the logo","Lays out the market, model, financials and go-to-market to win resources and align execution","Replaces testing","Sets salaries"], c:1, why:"It's the document that secures funding and coordinates the launch — story + numbers + plan."},
    {type:"mcq", tag:"M5 · emerging markets / BoP", t:"Products for emerging / base-of-pyramid markets must above all be:",
     o:["Premium and feature-rich","Affordable and rugged — designed for constraints (low income, weak infra), not stripped-down rich-world goods","Imported","Luxury"], c:1, why:"Win the BoP by designing for the context (affordability, durability, distribution), not by discounting premium goods."},
    {type:"mcq", tag:"M5 · design thinking", t:"Design thinking for NPD is:",
     o:["A linear checklist","A human-centred, iterative loop: empathise → define → ideate → prototype → test","A financial model","A launch tactic"], c:1, why:"Iterative and user-centred — cycle fast, learn, refine; not a one-pass process."},
    {type:"mcq", tag:"M5 · soft innovation", t:"'Soft innovation' (e.g. Luxottica's design/brand-led edge) under hyper-competition means innovating in:",
     o:["Only hard technology","Aesthetics, meaning, branding and experience — not just functional tech","Manufacturing only","Pricing only"], c:1, why:"When tech parity is common, soft (aesthetic/symbolic) innovation differentiates and defends margins."},
    // ===================== M6 · LAUNCH, DIFFUSION & PUBLIC POLICY =====================
    {type:"mcq", tag:"M6 · launch & platform decisions", t:"Strategic launch planning (incl. platform decisions) means deciding:",
     o:["The party venue","Strategic posture, target, timing and the product platform from which variants spring — before going live","The logo","The CEO's speech"], c:1, why:"A platform decision shapes all future derivatives; launch is strategy, not just a date."},
    {type:"mcq", tag:"M6 · target market", t:"Target-market decisions at launch should:",
     o:["Target everyone","Pick a focused beachhead segment you can win, then expand","Ignore segments","Copy rivals"], c:1, why:"Win one segment decisively (the beachhead) before broadening — scattering loses."},
    {type:"mcq", tag:"M6 · diffusion", t:"The diffusion 'chasm' sits between:",
     o:["Innovators and Early Adopters","Early Adopters and the Early Majority","Late Majority and Laggards","Early and Late Majority"], c:1, why:"Reaching the pragmatic Early Majority is the hard jump — cross it with a beachhead + references."},
    {type:"mcq", tag:"M6 · positioning", t:"Product positioning is best built as a chain of:",
     o:["Price → discount → sale","Feature → function → benefit (translate specs into customer value)","Logo → colour → font","Ad → ad → ad"], c:1, why:"Customers buy benefits, not features — positioning must end at the benefit that matters to them."},
    {type:"mcq", tag:"M6 · brand vs trademark", t:"Brand vs trademark — which is correct?",
     o:["They're identical","A brand is the perception/promise in customers' minds; a trademark is its legal protection","A trademark is the perception","A brand is a logo only"], c:1, why:"Brand = meaning; trademark = the legal mark. Naming and extension decisions leverage brand equity."},
    {type:"mcq", tag:"M6 · brand communities", t:"The 'myth' about brand communities is that:",
     o:["They don't exist","They're free and fully controllable — actually they're powerful but member-owned and can resist the firm","They never help","They're only online"], c:1, why:"Communities build loyalty but you don't own them — try to over-control and members push back."},
    {type:"mcq", tag:"M6 · pre-announcement & beachhead", t:"A pre-announcement and a 'beachhead / lean launch' are used to:",
     o:["Inflate the share price","Shape expectations / freeze buyers, then enter narrowly and learn before scaling (lean)","Skip testing","Avoid marketing"], c:1, why:"Pre-announce to influence the market; launch lean into a beachhead to de-risk the full rollout."},
    {type:"mcq", tag:"M6 · market testing", t:"Simulated, controlled and full test markets are methods of:",
     o:["Concept testing","Market testing — validating the full marketing mix before national launch","Prototyping","Alpha testing"], c:1, why:"Rising cost/realism; decide how much real-market proof you need before committing nationally."},
    {type:"mcq", tag:"M6 · launch management & metrics", t:"A launch-management system with innovation metrics exists to:",
     o:["Throw a party","Track early signals (trial, repeat, funnel) and react fast — and decide on product failure & deletion","Set the logo","Hire staff"], c:1, why:"Manage the launch like a live system; kill failures promptly (deletion) to free resources."},
    {type:"mcq", tag:"M6 · public policy lifecycle", t:"The 'public policy issue life cycle' warns firms that:",
     o:["Policy never changes","A concern moves from fringe → media → regulation, so anticipate it before it becomes law","Regulation is instant","Only lawyers care"], c:1, why:"Get ahead of emerging concerns (safety, environment) before they harden into binding rules."},
    {type:"mcq", tag:"M6 · product liability", t:"A consumer is injured by a defect. Liability WITHOUT proving carelessness is:",
     o:["Negligence","Strict liability","Breach of warranty","Caveat emptor"], c:1, why:"Strict liability: defect + harm is enough. Plus negligence, breach of warranty, and product recall as remedies."},
    {type:"mcq", tag:"M6 · sustainability & ethics", t:"Environmental concern and personal ethics in NPD mean designers should:",
     o:["Ignore externalities","Build for sustainability (lifecycle, materials, disposal) and act ethically beyond mere legal compliance","Maximise waste","Only obey the law"], c:1, why:"Sustainable design + ethics protect users, brand and planet — increasingly a source of advantage, not just cost."},
    // ===================== WRITTEN (actionable advice + examples) =====================
    {type:"written", t:"Explain the <b>10/100 rule (front-end loading)</b> and what it implies for running NPD.",
     looking:["~1× at idea stage, ~10× in late development, ~100× at launch","Late changes ripple through tooling, supply chain, committed marketing","Implication: invest in early-stage rigour (concept testing, protocol, cross-functional input)","Catching issues on paper is far cheaper than fixing them in market"],
     model:"The 10/100 rule captures how the cost of changing a spec escalates through the funnel: ~nothing at the idea stage, ~10× in late development, ~100× at launch — because late changes ripple through tooling, the supply chain and committed marketing. The implication is 'front-end loading': invest disproportionately early — rigorous concept testing, a clear product protocol, and cross-functional input — to lock requirements before money is sunk. Catching design issues on paper is vastly cheaper than fixing them after launch, so disciplined up-front work is the highest-return activity in NPD.",
     use:"Justify why early rigour pays; explain why 'Ready-Fire-Aim' launches are so costly."},
    {type:"written", t:"Explain the <b>Kano model's</b> three core categories with examples, and how to use it to prioritise features.",
     looking:["Must-be: absent → anger, present → neutral (brakes)","One-dimensional: more = better (battery life)","Delighter: absent → neutral, present → delight (surprise upgrade)","Sequence: secure must-bes → compete on one-dimensionals → differentiate with delighters","Delighters decay into expectations over time"],
     model:"Kano classifies features by how satisfaction responds to performance. Must-be (basic) features are expected: absence causes anger, presence only prevents dissatisfaction (brakes). One-dimensional (performance) features scale linearly — more is better (battery life). Delighters (attractive) are unexpected and delight when present but don't dissatisfy when absent (a surprise upgrade). A PM should first guarantee every must-be (a gap is fatal), then compete on the one-dimensionals customers compare, and finally differentiate with a delighter — refreshing the pipeline because delighters decay into expectations.",
     use:"Feature prioritisation and roadmaps; pairs with QFD (translate prioritised needs into specs)."},
    {type:"written", t:"Define and contrast <b>modular and integral</b> architecture with an example of each, and the trade-off.",
     looking:["Modular: standardised, decoupled interfaces — mix/match/upgrade (PC, bicycle)","Integral: tightly interdependent, optimised whole (iPhone, F1 car)","Modular buys variety/upgradability/lower change-cost","Integral buys performance/compactness/efficiency","Choose by what the customer values most"],
     model:"Modular architecture uses standardised, decoupled interfaces so components can be mixed, swapped and upgraded independently — a PC or a bicycle. Integral architecture has tightly interdependent components optimised together as one whole, maximising performance but costly to change — an iPhone's internals or an F1 car. The trade-off: modularity buys variety, customisation, upgradability, reuse and a lower cost of change at some cost to peak performance; integrality buys finely-tuned performance and compactness at the cost of flexibility. Choose modular when customers value variety/upgradability and you want many cheap variants; choose integral when performance is the decisive dimension.",
     use:"The flagship compare question; informs platform/variety strategy. Never reverse the poles."},
    {type:"written", t:"Distinguish <b>alpha, beta and gamma</b> testing and explain why they run in sequence.",
     looking:["Alpha = internal team, controlled conditions","Beta = real external users in natural environment","Gamma = final conformance to specs before launch","Sequence: realism and cost rise at each step — de-risk progressively"],
     model:"These are sequential use-tests. Alpha is internal, under controlled conditions, to catch obvious defects cheaply and early. Beta places the product with real external users in their natural environment, surfacing real-world usage problems a lab can't reveal. Gamma is the final verification that the product conforms to its specifications before full launch — vital in regulated or safety-critical products. They run in sequence because realism and cost rise at each step: it's far cheaper to fix internal bugs at alpha than to discover them in the field, so you de-risk progressively before a national launch.",
     use:"Any product-use-testing question; sits between prototyping and market testing. Don't confuse alpha (internal) with beta (external)."},
    {type:"written", t:"Explain the <b>Blue Ocean ERRC</b> framework and how it creates uncontested market space, with an example.",
     looking:["Blue ocean = uncontested space vs red-ocean competition","Eliminate / Reduce → cut cost","Raise / Create → lift buyer value","Breaks the value-cost trade-off; targets non-customers","Example: a low-cost airline (Southwest)"],
     model:"Blue Ocean strategy seeks uncontested 'blue' space instead of fighting in bloody 'red' oceans. ERRC reconstructs the value curve via four questions: which taken-for-granted factors to Eliminate, which to Reduce below the standard, which to Raise above it, and which entirely new factors to Create. Eliminate and Reduce strip cost; Raise and Create lift value — together breaking the value-cost trade-off, so a firm is both differentiated and lower-cost, opening demand among non-customers. For example, Southwest eliminated meals and seat classes and reduced hub complexity (cost) while creating high-frequency point-to-point flights and friendly speed (value).",
     use:"Any 'enter a crowded market' or 'create new demand' question; contrast with competing harder in a red ocean."},
    {type:"written", t:"Distinguish the three <b>PSS (Product-Service System)</b> types by who owns the asset, and explain the servitisation logic.",
     looking:["Product-oriented: customer owns it + add-on services","Use-oriented: provider owns the asset, customer pays to use","Result-oriented: customer buys the outcome, provider owns everything","Ownership/risk shift from customer to provider along product → use → result","Deeper servitisation = recurring revenue + provider aligned to outcome"],
     model:"PSS types differ by ownership and what the customer pays for. Product-oriented: the customer buys and owns the product, bundled with services. Use-oriented: the provider retains ownership and the customer pays for access/use (leasing, pay-per-wash), so the customer avoids capex and the provider keeps asset risk. Result-oriented: no specific product is sold — the customer buys a guaranteed outcome (Rolls-Royce 'Power by the Hour'), and the provider owns and manages everything, paid on results. As you move product → use → result, ownership and risk shift to the provider; servitisation deepens, turning one-off sales into recurring revenue and aligning the provider with the customer's outcome — but demanding the provider absorb more risk.",
     use:"Any servicing/business-model question for a physical product; explains the shift from selling products to selling outcomes."}
  ]
};
