(function () {
  "use strict";

  var catalogue = window.T6_COURSES || {};

  function rotateOptions(correct, wrong, shift) {
    var values = [correct].concat(wrong).slice(0, 4);
    var amount = ((shift % values.length) + values.length) % values.length;
    var options = values.slice(amount).concat(values.slice(0, amount));
    return {options: options, answer: options.indexOf(correct)};
  }

  function makeQuestion(courseId, concept, perspective, stem, correct, wrong, caselet, shift) {
    var set = rotateOptions(correct, wrong, shift);
    return {
      id: concept.id + "_" + perspective,
      courseId: courseId,
      conceptId: concept.id,
      module: concept.module,
      source: concept.source,
      node: concept.name,
      pattern: perspective === "explain" ? "Concept check" : perspective === "apply" ? "Application" : "Concept connection",
      perspective: perspective,
      caselet: caselet || "",
      stem: stem,
      options: set.options,
      answer: set.answer,
      explanation: concept.summary,
      link: concept.bridge
    };
  }

  /* Connect-question distractors.
   *
   * Every "connect" question asks the learner to pick the bridge statement, against
   * the same three misconceptions: a local optimum, a decision closed to evidence,
   * and an idea treated as context-free. Three FIXED strings used to serve all 48 of
   * them, and because a bridge runs 16-22 words while those strings ran 11-14, the
   * correct answer was the longest option in every connect question in the bank.
   * Lengthening them to a single mid-range size only moved the tell: the bridge then
   * landed at rank 3 in most questions and "pick the second-longest" replaced "pick
   * the longest".
   *
   * One fixed triple cannot straddle 48 different correct-answer lengths. So each
   * misconception carries three phrasings of the SAME claim at different lengths, and
   * the generator picks per concept so the bridge lands on a different rank each time.
   * The misconception a learner selects is identical whichever phrasing they saw, and
   * every phrasing maps to that misconception's diagnosis in `t6_diagnoses.js`. */
  var CONNECT_WRONG = [
    [ // local optimum
      "It improves one local measure, so effects elsewhere in the system stop mattering.",
      "It improves one local measure, so whatever happens elsewhere in the connected system no longer matters here at all.",
      "It improves one local measure, so whatever happens elsewhere in the connected system can be treated as somebody else's problem to solve later on."
    ],
    [ // decision closed to later evidence
      "Once this choice is made, later evidence should not change the decision.",
      "Once this choice has been made, later evidence should not be allowed to reopen or change the decision.",
      "Once this choice has been made, later evidence should not be allowed to reopen it, because a decision that keeps moving is not really a decision."
    ],
    [ // idea treated as context-free
      "It works independently of the people, the constraints, and the decisions around it.",
      "It works in exactly the same way independently of the people, the constraints, and the decisions that surround it.",
      "It works in exactly the same way regardless of the people involved, the constraints in force, and the decisions being taken around it at the time."
    ]
  ];

  function wordCount(value) {
    return String(value || "").trim().split(/\s+/).filter(Boolean).length;
  }

  /* Choose one phrasing per misconception so that `longerWanted` of the three run
   * longer than the bridge and the rest run shorter — which places the bridge at a
   * chosen rank once the options are sorted by length. The short phrasing is always
   * below a bridge and the long one always above it; the middle phrasing is used
   * whenever it falls on the required side, to keep the option set from reading as
   * two fixed extremes. */
  function connectWrong(bridge, longerWanted) {
    var target = wordCount(bridge);
    return CONNECT_WRONG.map(function (variants, index) {
      var wantLonger = index < longerWanted;
      var middle = wordCount(variants[1]);
      if (wantLonger) return middle > target ? variants[1] : variants[2];
      return middle < target ? variants[1] : variants[0];
    });
  }

  function makeCourse(config) {
    var questions = {};
    var byModule = {};
    config.concepts.forEach(function (concept, index) {
      byModule[concept.module] = byModule[concept.module] || [];
      byModule[concept.module].push(concept);

      var explain = makeQuestion(
        config.id, concept, "explain", "Which statement best explains " + concept.name + "?",
        concept.summary, concept.confusions, "", concept.module + index
      );
      var apply = makeQuestion(
        config.id, concept, "apply", "What is the best interpretation or next step?",
        concept.application, concept.applicationWrong, concept.caselet, concept.module + index + 1
      );
      var connect = makeQuestion(
        config.id, concept, "connect", "Which explanation best connects this idea to the wider subject?",
        concept.bridge,
        // Cycle the bridge across all four length ranks rather than pinning it to one.
        connectWrong(concept.bridge, index % 4),
        "A student understands the definition but needs to explain why the idea changes the next decision.",
        concept.module + index + 2
      );
      explain.repairId = apply.id;
      apply.repairId = connect.id;
      connect.repairId = explain.id;
      questions[explain.id] = explain;
      questions[apply.id] = apply;
      questions[connect.id] = connect;
    });

    config.synthesis.forEach(function (item, index) {
      var concept = config.concepts.filter(function (entry) { return entry.id === item.conceptId; })[0];
      var set = rotateOptions(item.correct, item.wrong, index + 1);
      questions[item.id] = {
        id: item.id,
        courseId: config.id,
        conceptId: item.conceptId,
        module: concept.module,
        source: item.source,
        /* A synthesis question discriminates between frameworks, so it may cite
         * more than the lecture its answer comes from. Declaring every lecture
         * it discriminates between gates it behind all of their lessons, and
         * naming the prerequisite concepts lets a miss route back to the
         * relationship rather than to the answer's concept alone. Defaults
         * preserve the previous single-source behaviour. */
        sourceIds: item.sourceIds || [item.source],
        supportingConceptIds: item.supportingConceptIds || [],
        node: item.node,
        pattern: "Mixed case",
        perspective: "synthesis",
        caselet: item.caselet,
        stem: item.stem,
        options: set.options,
        answer: set.answer,
        explanation: item.explanation,
        link: item.link,
        repairId: concept.id + "_apply"
      };
    });

    var runs = [];
    for (var module = 1; module <= 8; module += 1) {
      var moduleConcepts = byModule[module];
      runs.push({
        id: module,
        module: module,
        title: config.modules[module - 1],
        subtitle: moduleConcepts.map(function (concept) { return concept.name; }).join(" · "),
        minutes: 7,
        questionIds: moduleConcepts.reduce(function (ids, concept) {
          return ids.concat([concept.id + "_explain", concept.id + "_apply"]);
        }, [])
      });
    }
    runs.push({
      id: 9,
      module: 9,
      title: "Connect the whole subject",
      subtitle: "One cause-and-effect question from every module",
      minutes: 11,
      questionIds: config.concepts.filter(function (_, index) { return index % 2 === 0; }).map(function (concept) { return concept.id + "_connect"; })
    });
    runs.push({
      id: 10,
      module: 10,
      title: "Full practice mock",
      subtitle: "Twelve mixed concept and case questions",
      minutes: 18,
      mock: true,
      questionIds: config.concepts.filter(function (_, index) { return index % 2 === 1; }).map(function (concept) { return concept.id + "_connect"; })
        .concat(config.synthesis.map(function (item) { return item.id; }))
    });

    return {
      id: config.id,
      title: config.title,
      shortTitle: config.shortTitle,
      description: config.description,
      modules: config.modules,
      chain: config.modules,
      concepts: config.concepts,
      runs: runs,
      questions: questions
    };
  }

  function enrichBrgsa(course) {
    var concepts = [
      {id:"brgsa_m1_demand",module:1,source:"BRGSA-M01-L01",name:"Demand validation",match:/lean|validat|landing|smoke|survey/i},
      {id:"brgsa_m1_evidence",module:1,source:"BRGSA-M01-L04",name:"Strength of evidence",match:/commit|pre.order|evidence|signal/i},
      {id:"brgsa_m2_design",module:2,source:"BRGSA-M02-L01",name:"Experiment design",match:/null|sample|experiment|proxy/i},
      {id:"brgsa_m2_error",module:2,source:"BRGSA-M02-L03",name:"Decision errors",match:/type|error|false|cost/i},
      {id:"brgsa_m3_cohort",module:3,source:"BRGSA-M03-L01",name:"Cohorts and retention",match:/cohort|retention|shape/i},
      {id:"brgsa_m3_economics",module:3,source:"BRGSA-M03-L04",name:"CAC and LTV",match:/cac|ltv|economic|scale/i},
      {id:"brgsa_m4_constraint",module:4,source:"BRGSA-M04-L02",name:"Growth constraint",match:/constraint|discipline|stage/i},
      {id:"brgsa_m4_customers",module:4,source:"BRGSA-M04-L04",name:"First customers",match:/customer|founder|acqui/i},
      {id:"brgsa_m5_channel",module:5,source:"BRGSA-M05-L01",name:"Channel fit",match:/channel|outbound|organic|loop/i},
      {id:"brgsa_m5_activation",module:5,source:"BRGSA-M05-L05",name:"Activation",match:/aha|activat|friction/i},
      {id:"brgsa_m6_habit",module:6,source:"BRGSA-M06-L01",name:"Habit and lifecycle",match:/habit|lifecycle|retention/i},
      {id:"brgsa_m6_churn",module:6,source:"BRGSA-M06-L05",name:"Churn and referral",match:/churn|referral|network/i},
      {id:"brgsa_m7_pricing",module:7,source:"BRGSA-M07-L01",name:"Pricing and NRR",match:/pricing|nrr|revenue/i},
      {id:"brgsa_m7_pipeline",module:7,source:"BRGSA-M07-L04",name:"Pipeline and payback",match:/pipeline|handoff|payback|motion/i},
      {id:"brgsa_m8_priority",module:8,source:"BRGSA-M08-L01",name:"Prioritisation",match:/ice|backlog|priorit|allocation/i},
      {id:"brgsa_m8_decision",module:8,source:"BRGSA-M08-L03",name:"Decision rules",match:/decision|rule|vanity|metric/i}
    ];
    var modules = ["Validate demand", "Design fair tests", "Read the evidence", "Find the growth constraint", "Acquire and activate", "Retain customers", "Price and sell", "Operate the system"];
    Object.keys(course.questions).forEach(function (id) {
      var question = course.questions[id];
      var sourceModule = Number((String(question.source).match(/-M(\d\d)-/) || [0, question.module])[1]);
      var module = sourceModule >= 1 && sourceModule <= 8 ? sourceModule : Math.min(8, Math.max(1, question.module || 1));
      var candidates = concepts.filter(function (concept) { return concept.module === module; });
      var text = [id, question.node, question.stem].join(" ");
      var concept = candidates.filter(function (entry) { return entry.match.test(text); })[0] || candidates[id.length % candidates.length];
      question.courseId = "BRGSA";
      question.conceptId = concept.id;
      question.perspective = /case|application|decision|synthesis/i.test(question.pattern || "") ? "apply" : "explain";
    });
    concepts.forEach(function (concept) { delete concept.match; });
    course.description = "Business research, growth decisions, customer behaviour, and analytics.";
    course.modules = modules;
    course.chain = modules;
    course.concepts = concepts;
    course.runs[8].title = "Connect the whole subject";
    course.runs[8].subtitle = "One cause-and-effect question from every module";
    course.runs[9].title = "Full practice mock";
    course.runs[9].subtitle = "Twelve mixed concept and case questions";
    return course;
  }

  if (window.T6_COURSE) catalogue.BRGSA = enrichBrgsa(window.T6_COURSE);

  catalogue.IBM = makeCourse({
    id: "IBM",
    title: "Inclusive Business Models",
    shortTitle: "IBM",
    description: "How financially sustainable organisations serve underserved people and measure real impact.",
    modules: ["Inclusive business basics","Affordable health and education","Responsible finance and agriculture","Rural employment models","Shared value and energy access","Informal work and waste","Farmer organisations and social business","Impact investment and measurement"],
    concepts: [
      {id:"ibm_inclusive",module:1,source:"IBM-M01-L03",name:"Inclusive business",summary:"An inclusive business is built to meet a specific need of underserved people while remaining financially sustainable.",confusions:["Any profitable firm is inclusive if it sells a useful product to anyone who needs it.","An inclusive business must maximise shareholder profit first and treat social outcomes as whatever remains once returns are secured.","Only grant-funded charities can be inclusive, because charging a customer anything ends the social purpose."],caselet:"A clinic serves low-income districts, charges enough to cover operations, and reinvests to expand access.",application:"Treat it as an inclusive business because serving an underserved need is the primary purpose and the model is designed to sustain itself.",applicationWrong:["Treat it as ordinary CSR, because social activity always sits outside the business model and is funded from profit.","Reject it as inclusive, because charging any fee to an underserved customer cancels the social purpose the model was built to serve.","Call it inclusive only if shareholder return is its sole objective, since financial discipline is what separates a real business from charity."],bridge:"Financial sustainability keeps the social solution available; the underserved need determines what the model is built to do."},
      {id:"ibm_bop",module:1,source:"IBM-M01-L07",name:"Bottom-of-the-pyramid design",summary:"Serving bottom-of-the-pyramid markets requires products, prices, and delivery systems redesigned for structural constraints rather than smaller copies of rich-market offers.",confusions:["The model depends only on very high margins per customer, since poor households buy rarely and must be charged more.","A product becomes inclusive as soon as it is sold in a developing economy, regardless of its price or design.","Existing premium products can be moved unchanged into poorer markets, because a good product sells wherever there is genuine unmet need."],caselet:"A company wants rural adoption but its pack size, payment schedule, and service network assume high monthly income and urban access.",application:"Redesign affordability, access, and service around the market's constraints before treating population size as demand.",applicationWrong:["Keep the offer unchanged, because a large population guarantees enough buyers will convert.","Raise the pack size so each individual sale produces a larger absolute margin for the firm.","Target only wealthy urban buyers while still describing the offer as a bottom-of-the-pyramid model in reporting."],bridge:"A large underserved population becomes a market only when the offer removes the affordability and access barriers that suppress use."},
      {id:"ibm_vaatsalya",module:2,source:"IBM-M02-L04",name:"No-frills healthcare access",summary:"Vaatsalya placed low-cost primary and secondary hospitals in semi-urban areas to reduce the travel and access burden faced by underserved patients.",confusions:["Its main advantage was adding premium tertiary care in major cities where specialist demand is already concentrated.","It solved access by arranging transport so every rural patient could reach an existing tertiary hospital in the nearest city.","The model depended on avoiding quality controls so that costs could be cut far enough to reach much poorer patients."],caselet:"A hospital chain sees rural patients travelling hours for routine and secondary care while city hospitals remain crowded.",application:"Locate a focused, quality-controlled facility nearer the underserved population and design its costs around essential care.",applicationWrong:["Open another premium tertiary hospital in the city and let patients travel to it.","Remove trained staff so the price falls, on the view that cost is the only barrier patients actually face.","Offer only a transport subsidy without addressing whether local care capacity exists at all."],bridge:"Where care is located changes who can use it; cost discipline matters only if essential quality and access remain intact."},
      {id:"ibm_aravind",module:2,source:"IBM-M02-L08",name:"Process specialisation in healthcare",summary:"Aravind increased cataract capacity by standardising pre- and post-operative work for trained paramedics while surgeons focused on the surgery itself.",confusions:["Every activity stayed with the surgeon so that consistency and utilisation of the specialist were both preserved.","Capacity increased mainly by reducing the number of patients treated so each case could be given longer.","The model removed clinical judgement from the surgical step itself and turned the operation into a routine task anyone could repeat."],caselet:"A scarce surgeon spends much of the day on repeatable preparation and follow-up while patients wait for operations.",application:"Separate standardisable tasks for trained support staff so the specialist concentrates on the constrained surgical step.",applicationWrong:["Ask the surgeon to perform every task personally so the whole process stays consistent.","Reduce theatre use so that staff have more idle time between cases and mistakes fall.","Let untrained staff perform the surgery as well as the preparation, since the whole cycle is standardised."],bridge:"Specialisation raises throughput when routine work is separated from the scarce expert task without lowering clinical quality."},
      {id:"ibm_grameen",module:3,source:"IBM-M03-L03",name:"Group-based microfinance",summary:"The classic Grameen model used local group knowledge, sequential lending, meetings, and peer accountability to lend without traditional collateral.",confusions:["It replaced borrower assessment altogether with unlimited individual lending to anyone who asked for it in the village.","It depended on a formal credit bureau to select every village borrower before any loan was made.","All group members received large loans at the same time without conditions, so nobody had to wait for anyone else's repayment."],caselet:"A lender cannot observe rural borrowers well and conventional collateral is unavailable, but neighbours know each other's reliability.",application:"Use carefully formed groups, staged lending, and local monitoring to make community knowledge part of risk assessment.",applicationWrong:["Issue repeated loans without checking repayment capacity, because a good repayment record settles the question.","Ignore what the group knows and lend against sales-agent targets instead, since loan volume proves the model is working.","Require urban property collateral from every applicant, since no loan is safe without a registered asset."],bridge:"Local information can reduce screening risk, but the structure works only when repayment capacity and group discipline remain real."},
      {id:"ibm_responsible_lending",module:3,source:"IBM-M03-L05",name:"Responsible lending",summary:"Responsible lending checks total debt and repayment capacity instead of rewarding loan volume that can push households into over-indebtedness.",confusions:["More simultaneous loans always prove stronger financial inclusion, because access to more credit is what inclusion is measuring.","A prior lender's approval removes the need for fresh due diligence, since somebody has already checked this household's finances carefully.","Sales incentives are a reliable substitute for capacity checks, because officers will not lend where repayment looks doubtful to them."],caselet:"A household uses a new microloan to repay several older microloans, while agents are paid for each additional disbursement.",application:"Pause new lending, assess total obligations and cash flow, and correct incentives that reward volume over borrower capacity.",applicationWrong:["Approve quickly, because the earlier lenders must already have checked this household's total obligations and cash flow.","Add another loan so the household can keep up its existing repayments for a few more months.","Judge success only by the number of accounts opened, since reach is the outcome this programme was set up to deliver."],bridge:"Access becomes harmful when debt service outruns income; scale must preserve the screening practices that made inclusion viable."},
      {id:"ibm_rural_bpo",module:4,source:"IBM-M04-L04",name:"Rural BPO model",summary:"RuralShores adapted BPO work, training, language, location, and employment practices to rural conditions while competing on service quality.",confusions:["It copied an urban international-call-centre model without changes and simply moved it to a village.","Its clients accepted poor service because the mission was social and the contract supported rural employment in the region.","It created impact mainly by selling consumer goods to rural workers rather than by employing them in skilled work."],caselet:"A rural centre has capable local youth and multilingual demand, but international voice work and urban shift norms are a poor fit.",application:"Choose suitable domestic processes, train local staff, and adapt operations without relaxing client service standards.",applicationWrong:["Compete only for English-heavy international voice work, since that is where the margins sit.","Ask clients to accept lower service quality as their social contribution towards creating rural employment.","Move the centre to a metro while retaining the rural label in all client reporting and marketing."],bridge:"The model creates employment because business processes are redesigned around local capability while market-facing quality remains credible."},
      {id:"ibm_replication",module:4,source:"IBM-M04-L05",name:"Replicating rural services",summary:"Rural service models scale through trusted local partners, standard quality, training, and complementary relationships rather than capital-heavy central control alone.",confusions:["Replication means every centre must be owned and run directly by the parent organisation to hold quality.","Local partners matter only after national scale is reached, since early growth depends entirely on central capital and control.","Low price alone is enough to win outsourced critical work, because clients ultimately buy on cost rather than on demonstrated capability."],caselet:"A rural BPO wants to enter many small towns but lacks local knowledge and cannot fund every centre itself.",application:"Use a controlled partner model with local credibility, training, certification, and shared operating standards.",applicationWrong:["Own every centre directly regardless of the capital required or local acceptance.","Let each partner invent its own service standards independently of any shared certification requirement.","Rely only on price discounts to win contracts and omit quality certification from the model entirely."],bridge:"Local partnership lowers entry friction and capital needs; common standards stop distributed growth from weakening trust."},
      {id:"ibm_shared_value",module:5,source:"IBM-M05-L07",name:"Shared value",summary:"Shared value expands economic value by solving social problems through the business model so stakeholders beyond shareholders benefit from the value created.",confusions:["It is simply redistributing profit at the end of the year while harmful operations continue unchanged elsewhere in the business.","Any profitable activity creates shared value automatically, because a growing firm eventually lifts everyone who is connected to it.","It requires the firm to stop earning a return, since a genuine social contribution cannot also be profitable for shareholders at the same time."],caselet:"A buyer raises farmer productivity and product quality, lowering supply risk while farmers earn more.",application:"Evaluate whether the operating model creates additional value for both the firm and farmers rather than merely donating after profit is made.",applicationWrong:["Count it as shared value only if the firm loses money on the arrangement, since financial sacrifice is what proves sincerity.","Ignore farmer outcomes altogether, because the firm's own profitability already proves the shared-value claim.","Classify any statutory donation as an integrated supply-chain model, since the money reaches the same community either way."],bridge:"The business becomes more durable when solving a stakeholder constraint also strengthens the economics that fund the solution."},
      {id:"ibm_selco",module:5,source:"IBM-M05-L10",name:"SELCO affordability system",summary:"SELCO linked customised solar products with independent finance and reliable service so energy access could support income and repay its own cost.",confusions:["Affordability meant giving every customer the same free product regardless of what their own work actually required.","SELCO maximised sales by approving its own customer loans as well as supplying, installing, and servicing the equipment itself.","After-sale service was optional because solar equipment carries no downtime risk once it has been correctly installed the first time."],caselet:"A street vendor spends ₹15 a day on kerosene and could use a solar light financed at ₹10 a day, provided failures are repaired quickly.",application:"Bundle a suitable light with third-party finance and dependable service, linking repayment to the customer's savings or added income.",applicationWrong:["Sell the largest system available and let SELCO approve the customer's debt itself rather than a bank.","Ignore servicing once the purchase is complete, because the sale has already been recorded and paid for.","Require the full price upfront despite the customer's daily cash flow, since arranging third-party finance only complicates and delays the sale."],bridge:"Product, finance, livelihood benefit, and uptime form one affordability system; removing any link can make the offer unusable."},
      {id:"ibm_labournet",module:6,source:"IBM-M06-L02",name:"LabourNet platform",summary:"LabourNet sought to improve informal workers' mobility through identity, skills, market links, and institutional access while building a sustainable enterprise.",confusions:["It addressed informal work only by issuing one-time cash grants to workers who registered on the platform.","Its model assumed migrant workers already had trusted identities and bank access before they arrived in the city.","The platform worked by preventing workers from changing employers, so that placements would remain stable for the firms hiring them over time."],caselet:"Migrant workers spend time finding jobs, lack verifiable identity, and are treated as high risk by formal institutions.",application:"Build trusted worker records, skills, job-market connections, and links to financial or insurance institutions together.",applicationWrong:["Offer a job listing service without solving the identity or trust problem underneath it.","Exclude the most mobile workers, because keeping records on them is difficult.","Measure impact only by the number of registrations recorded, not by what changed for the worker."],bridge:"Identity makes skills and work history legible; that trust opens market and institutional access that income mobility requires."},
      {id:"ibm_waste",module:6,source:"IBM-M06-L05",name:"Inclusive waste enterprise",summary:"An inclusive waste enterprise must create environmental value and viable products while protecting livelihoods and agency for waste workers.",confusions:["Selling recycled products is sufficient even if the waste workers themselves end up worse off than they were before collection started.","Environmental benefit cancels the need for financial viability, because the ecological case alone justifies keeping the enterprise running.","Workers can only ever participate as low-paid employees, never as owners or decision-makers in the enterprise they supply."],caselet:"A venture turns temple flower waste into incense and natural dyes using women from low-income communities.",application:"Track pollution reduction, product economics, and whether workers gain fair, durable livelihood opportunities.",applicationWrong:["Claim inclusion from the recycling volume alone, without reporting any worker outcomes.","Ignore product demand entirely, because environmental intent guarantees that the enterprise will survive on its own.","Replace livelihood measures with the total tonnage of waste collected each month."],bridge:"Waste becomes shared value only when material recovery, customer demand, and worker welfare reinforce one another."},
      {id:"ibm_fpo",module:7,source:"IBM-M07-L04",name:"Farmer Producer Organisation",summary:"An FPO pools farmer ownership, volume, services, and market links so smallholders can build a viable business and stronger bargaining position.",confusions:["An FPO is owned by an outside trader who buys the crop from the member farmers directly.","Its main purpose is to keep every farmer selling separately so each can negotiate their own price with the buyer.","Market linkage becomes unnecessary once farmers contribute equity, since ownership on its own secures a better price at the market."],caselet:"Small farmers produce a distinctive rice but individually lack volume, branding, advice, and negotiating power.",application:"Aggregate through a farmer-owned organisation, build traceability and market links, and invest in value-adding capability.",applicationWrong:["Keep volumes fragmented and negotiate farm by farm with each buyer as the season goes on.","Transfer ownership entirely to a distant buyer who already has market access.","Focus on registration counts and member numbers without building any sales or value-adding capability."],bridge:"Collective ownership turns fragmented production into scale, but market access and managerial capability convert that scale into income."},
      {id:"ibm_social_business",module:7,source:"IBM-M07-L05",name:"Social business",summary:"A social business prioritises social impact, aims not to make losses, and integrates the social purpose into operations rather than treating it as separate charity.",confusions:["It maximises distributable profit for its owners and treats social impact as an optional extra alongside the main commercial objective.","It is identical to employee volunteering, since both put company time and resources behind a social cause outside the business.","It must depend permanently on grants and cannot earn revenue, because charging its customers anything would compromise the social mission it was set up to serve."],caselet:"A company creates a business line for affordable nutrition whose goal is impact, while prices cover costs and profits are not the primary objective.",application:"Judge it by whether the social goal drives the model and financial discipline keeps it operating without turning profit maximisation into the purpose.",applicationWrong:["Call it ordinary CSR because it sells a product, and treat the stated social goal as a marketing position.","Require maximum dividends to shareholders before considering impact, since any business must first satisfy the owners who funded it.","Treat continuing losses as proof that the model is socially serious, since any profit would suggest the social mission had slipped."],bridge:"A social purpose becomes repeatable when it sits inside a no-loss operating model instead of depending only on periodic donations."},
      {id:"ibm_impact_investing",module:8,source:"IBM-M08-L01",name:"Impact investing",summary:"Impact investing intentionally targets measurable social or environmental impact alongside a financial return; it is not a grant.",confusions:["Any investment in a profitable company is an impact investment, because profitable firms create jobs and pay taxes.","Impact intent matters, but measurement and reporting do not, since the aim is what defines the investment.","Impact investing excludes all financial return, since accepting a return would make it ordinary commercial capital rather than philanthropy."],caselet:"A fund invests in affordable housing, sets access targets, reports outcomes, and expects the capital to earn a return.",application:"Classify it as impact investing because intent, measurement, and financial return are designed together.",applicationWrong:["Classify every housing share purchase as impact investing, whatever the intent behind it.","Treat it as philanthropy because it has a social target, and expect no financial return at all.","Ignore outcome reporting once the capital has been deployed and the investment is live."],bridge:"Intent defines the desired change, measurement tests whether it occurred, and return keeps investment capital reusable."},
      {id:"ibm_impact_measurement",module:8,source:"IBM-M08-L05",name:"Impact measurement",summary:"Credible impact measurement compares outcomes against a suitable counterfactual so changes caused by the intervention are not confused with selection or outside factors.",confusions:["A before-and-after increase always proves causation, because the observed change happened after the programme began in the village.","Participants can be compared with any convenient non-participant group, since anyone outside the programme can serve as a control.","Self-selection improves causal confidence, because the most motivated participants change more and therefore show the effect more clearly."],caselet:"Borrowers who choose a programme earn more later, but they were more enterprising than non-borrowers before it began.",application:"Use a comparable control or another defensible counterfactual and account for selection before attributing the income change to the programme.",applicationWrong:["Attribute the full income difference to the loan immediately, without asking what else changed for these households.","Compare the participants with a richer, unrelated village that was never offered the programme.","Use only participant testimonials as causal proof, since the people involved know best what actually changed in their own household finances."],bridge:"A counterfactual separates change caused by the intervention from change that would have happened because of who participated or what else changed."}
    ],
    synthesis: [
      {id:"ibm_syn_access",conceptId:"ibm_aravind",source:"IBM-M02-L08",node:"Access and process",caselet:"A low-cost clinic is near its patients but the only specialist still performs every routine task.",stem:"Which change best joins access with operating capacity?",correct:"Keep the local access model and move standard preparation and follow-up to trained staff so the specialist handles the constrained procedure.",wrong:["Move the clinic back to a premium city location where specialists already prefer to live and work.","Let the price fall by removing quality checks, since affordability is the only barrier these patients actually face.","Increase advertising spend without changing the bottleneck, because more incoming demand will lift the number of procedures each week."],explanation:"Location solves access; task specialisation solves the scarce-capacity constraint.",link:"Inclusive access holds only when the delivery process can serve demand at reliable quality."},
      {id:"ibm_syn_scale",conceptId:"ibm_responsible_lending",source:"IBM-M03-L05",node:"Scale without harm",caselet:"A lender doubles outreach by paying agents per loan while dropping group meetings and total-debt checks.",stem:"What is the central risk?",correct:"Scale has removed the screening and accountability that made lending inclusive, so outreach can become over-indebtedness.",wrong:["The model is safer, because more loans across more lenders always diversify a household's risk.","The only issue is that group meetings reduce the reach of the lender's advertising.","Repayment capacity matters only once a default has actually occurred and losses appear in the book."],explanation:"Inclusive scale must preserve borrower protection and repayment-capacity checks.",link:"Growth that destroys the protective mechanism is not replication of the original model."},
      {id:"ibm_syn_value",conceptId:"ibm_shared_value",source:"IBM-M05-L07",node:"Value and inclusion",caselet:"A buyer's new process cuts its costs but pushes all weather and price risk onto small farmers.",stem:"Why is a shared-value claim weak?",correct:"The firm gained through risk transfer rather than creating additional value that also improves farmer outcomes.",wrong:["Shared value requires the buyer to make no profit on the arrangement at all.","Any supply-chain change is automatically inclusive as long as farmers are involved somewhere in it.","Only donations can benefit farmers, since a commercial relationship always extracts more value than it gives back."],explanation:"Shared value expands value for connected stakeholders instead of extracting it from a weaker one.",link:"Profit and social benefit must arise from the same improved system, not from shifting harm."},
      {id:"ibm_syn_impact",conceptId:"ibm_impact_measurement",source:"IBM-M08-L05",node:"Finance to evidence",caselet:"An impact fund reports how many enterprises it financed but not whether intended social outcomes changed.",stem:"What is missing?",correct:"Outcome measurement against a credible baseline or comparison, not just a count of financial activity.",wrong:["A larger total invested each year, which automatically proves that impact has been achieved.","Removal of the financial-return target, so that the capital simply counts as philanthropy instead.","A written record of every investor's personal motivation for putting money into the fund in the first place."],explanation:"Money deployed is an input; impact is the change that can reasonably be attributed to the financed activity.",link:"Impact investing becomes accountable when intentional capital is followed by credible outcome evidence."}
    ]
  });

  catalogue.SCLM = makeCourse({
    id:"SCLM",title:"Supply Chain and Logistics Management",shortTitle:"SCLM",description:"How demand, inventory, sourcing, transport, and coordination shape service and cost.",
    modules:["Strategy and performance drivers","Forecasting and planning","Inventory decisions","Sourcing and coordination","Re-engineering the network","Capacity and transport turnaround","Multimodal logistics and ports","Public logistics systems"],
    concepts:[
      {id:"sclm_fit",module:1,source:"SCLM-M01-L04",name:"Strategic fit",summary:"Strategic fit aligns the supply chain's efficiency and responsiveness with the customer promise and its implied uncertainty.",confusions:["Every supply chain should maximise responsiveness regardless of cost, because faster service always wins more customers than price does.","Competitive strategy and supply-chain design can be set independently, since marketing owns the promise and operations owns cost.","Stable demand always means low implied uncertainty, because uncertainty is a property of volume alone."],caselet:"Marketing promises high variety and same-day availability while operations uses slow transport, long batches, and suppliers chosen only for low price.",application:"Redesign the supply chain for the promised responsiveness or change the customer promise so capabilities and expectations match.",applicationWrong:["Keep both strategies unchanged, because each function is already locally efficient on its own budget and targets.","Add more product variety and same-day options without changing transport, batch sizes, or supplier selection.","Measure suppliers only on unit purchase price and ignore availability, because the lowest landed cost defines a fit supply chain."],bridge:"The customer promise creates operating requirements; performance fails when the network is built for a different promise."},
      {id:"sclm_drivers",module:1,source:"SCLM-M01-L06",name:"Six supply-chain drivers",summary:"Facilities, inventory, transportation, information, sourcing, and pricing jointly set the balance between responsiveness and efficiency.",confusions:["Transportation speed alone determines supply-chain performance, because every other driver simply follows the delivery schedule.","Adding facilities always lowers both total cost and total inventory, since local stock is cheaper to hold.","Each driver can be optimised independently, so the best network is the sum of six separate local optima."],caselet:"A quick-commerce firm adds small local fulfilment points and more local stock to reduce delivery time.",application:"Recognise a facilities-and-inventory choice that raises responsiveness while also increasing fixed cost and possibly total inventory.",applicationWrong:["Treat delivery speed as a free result of branding, since perception rather than network design sets service.","Assume more local facilities reduce every cost line, so their fixed cost needs no separate check.","Ignore information and sourcing because siting stock close to customers guarantees service on its own."],bridge:"Managers deliver strategic fit by configuring several connected drivers, not by maximising one lever in isolation."},
      {id:"sclm_smoothing",module:2,source:"SCLM-M02-L06",name:"Exponential smoothing",summary:"Exponential smoothing updates the old forecast by a fraction alpha of the latest forecast error; a larger alpha reacts more strongly to recent demand.",confusions:["It discards the old forecast entirely and sets the next forecast to the latest actual demand, so history carries no weight.","A larger alpha always produces a smoother and slower response, because alpha measures how much of the old forecast is retained.","The next forecast moves opposite to the latest error, so demand running above forecast pulls the following period's forecast down."],caselet:"Last period's forecast was 100, actual demand was 120, and alpha is 0.25.",application:"Move the next forecast upward by 25% of the 20-unit error, giving 105.",applicationWrong:["Set the next forecast to 120, because the latest actual replaces the old forecast entirely.","Move the forecast down to 95, applying the 25% adjustment against the direction of the error.","Keep it at 100, because smoothing averages past demand and never responds to a single period's error."],bridge:"Forecast error is the signal; alpha controls how quickly planning responds without throwing away accumulated history."},
      {id:"sclm_sop",module:2,source:"SCLM-M02-L12",name:"Sales and operations planning",summary:"S&OP balances forecast demand with capacity, utilisation, inventory, backlog, and outsourcing over a medium-term horizon.",confusions:["It is a daily dispatch schedule for today's orders and makes no capacity or inventory decisions.","A chase plan holds workforce and output constant while inventory absorbs every change in demand.","A level plan changes capacity every period to match demand exactly, hiring and releasing as the forecast moves."],caselet:"A plant with costly hiring and training faces seasonal demand, while its product can be stored economically.",application:"Use a more level production plan and build or draw down inventory, possibly mixing limited overtime or outsourcing.",applicationWrong:["Hire and release workers to match each monthly demand change exactly, since matching output to demand avoids holding inventory.","Ignore the forecast until daily orders arrive, because only confirmed orders justify committing capacity.","Absorb the whole peak with backlog even where customers will not tolerate delay, since backlog costs nothing to hold."],bridge:"Forecasts become decisions only when demand is reconciled with the real cost and flexibility of capacity, inventory, and service."},
      {id:"sclm_eoq",module:3,source:"SCLM-M03-L03",name:"Economic order quantity",summary:"EOQ chooses an order size that balances annual ordering cost against holding cost under stable demand, lead time, price, and no-shortage assumptions.",confusions:["EOQ is designed for a single buying opportunity under uncertain seasonal demand, where leftovers are marked down afterwards.","The model assumes frequent planned stockouts and quantity discounts that change the unit price as order size grows.","The largest order the supplier will accept is always optimal, because fewer orders each year always means a lower total annual cost."],caselet:"A component has stable annual demand, fixed cost per order, constant lead time, no discounts, and known annual holding cost.",application:"Use EOQ for the lot size, while calculating reorder timing separately from demand during lead time.",applicationWrong:["Use a newsvendor critical ratio to set the recurring order size, since both models choose a quantity under cost pressure.","Order a full year's demand in one lot, because a single ordering charge always beats twelve smaller ones.","Treat the EOQ quantity as the reorder point itself, so replenishment starts when stock falls to that number."],bridge:"Lot size sets the ordering-versus-holding trade-off; reorder timing answers a different question about when replenishment must start."},
      {id:"sclm_newsvendor",module:3,source:"SCLM-M03-L05",name:"Newsvendor decision",summary:"The newsvendor model chooses a one-time quantity under uncertain demand by balancing the cost of one unit too few against one unit too many.",confusions:["It assumes demand is constant and replenishment repeats indefinitely, so the same quantity is reordered in every cycle of the year.","Only the purchase cost of the item matters here, because salvage value and lost margin sit outside the ordering decision altogether.","Underage and overage costs push the order quantity in the same direction, so raising either of them raises the quantity that should be ordered this season."],caselet:"A seller must choose one order for a short season; leftovers are discounted and unmet demand loses contribution and goodwill.",application:"Use a critical-ratio decision based on underage and overage costs to select the demand quantile.",applicationWrong:["Use EOQ, because the item is inventory and a lot-size formula applies to any stocking decision.","Order the mean forecast quantity regardless of margin and salvage value, since the average is the best single estimate.","Ignore lost margin because only leftover stock carries a visible cost at the end of the season."],bridge:"The economic cost of being short versus long determines which point in the uncertain demand distribution is worth covering."},
      {id:"sclm_portfolio",module:4,source:"SCLM-M04-L04",name:"Tailored sourcing portfolio",summary:"A sourcing portfolio matches responsive sources to volatile, high-value or time-sensitive items and efficient sources to stable, predictable volume while managing disruption risk.",confusions:["One globally cheapest supplier is best for every item, because unit price is the only sourcing dimension that reaches the income statement.","Innovative products with short lives must always be sourced fully offshore, since low labour cost matters most where margins are thin.","Nearshoring removes every cost and disruption trade-off at once, so a closer supplier needs no comparison against a cheaper distant one on total cost."],caselet:"A firm sells one mature high-volume item and one volatile product with short life, high stockout cost, and frequent engineering changes.",application:"Use a low-cost source for stable volume and a faster, collaborative source for the volatile item, with risk hedges where justified.",applicationWrong:["Place both items with the longest-lead, lowest-price supplier, because a single consolidated relationship simplifies management and maximises volume leverage on unit price.","Reserve the responsive, collaborative source for the stable commodity and leave the volatile item on the slow low-price supplier.","Choose suppliers on landed cost alone, without weighing disruption exposure or the obsolescence risk carried by a short-life product."],bridge:"Different demand and product risks require different source capabilities; a portfolio prevents one cost objective from governing every item."},
      {id:"sclm_bullwhip",module:4,source:"SCLM-M04-L05",name:"Bullwhip effect",summary:"The bullwhip effect is the amplification of order variability upstream even when end-customer demand changes only modestly.",confusions:["It is the fall in transport cost that stable ordering produces once each stage batches its shipments efficiently.","Upstream orders are always less variable than retail sales, because each stage smooths what it passes on.","It occurs only when final consumer demand itself swings sharply, so a stable retail pattern rules the effect out."],caselet:"Retail sales move slightly, but retailer, wholesaler, and manufacturer orders show progressively larger peaks and troughs.",application:"Diagnose demand amplification and examine incentives, batching, forecast updates, lead times, and information distortion across stages.",applicationWrong:["Assume consumer demand moved by the same amount, and read the manufacturer's order swings as a true demand signal.","Ask each stage to optimise its own profit without sharing demand data, since local accountability serves the chain best.","Add more safety stock at every stage without addressing the order distortion that created the swings."],bridge:"Small local reactions compound across stages; coordination and shared demand signals stop defensive decisions from amplifying uncertainty."},
      {id:"sclm_reengineering",module:5,source:"SCLM-M05-L06",name:"Supply-chain re-engineering",summary:"Re-engineering redesigns end-to-end flows to remove hidden time, inventory, hand-offs, and cost while meeting distinct customer service needs.",confusions:["It means cutting one department's budget without examining the stages upstream and downstream of it.","More inventory is the default answer to every service problem, because stock is what protects a customer from delay.","Customer segments should receive identical logistics regardless of need, since one uniform service level is simplest to run and audit."],caselet:"A firm has long queues between stages, excess stock, repeated handling, and customers with very different speed requirements.",application:"Map the full flow, expose waiting and indirect costs, segment service needs, and redesign the connected process rather than one function.",applicationWrong:["Optimise each warehouse separately against its own cost target and leave the upstream effects of those choices unexamined.","Add buffer stock at every hand-off so no stage ever waits, and treat the resulting inventory as the cost of good service.","Give every segment the most expensive service level, since a uniformly high standard cannot disappoint any customer group."],bridge:"Time and inventory hide between organisational boundaries; end-to-end redesign makes those costs and customer trade-offs visible."},
      {id:"sclm_stockyard",module:5,source:"SCLM-M05-L13",name:"Stockyard location trade-off",summary:"Stockyard design balances primary and secondary transport cost, service-distance limits, throughput constraints, and inventory instead of choosing the fewest sites automatically.",confusions:["The geographically central site is always optimal, because the shortest average distance to demand settles the location question.","Primary and secondary movement cost the same per unit moved in every scenario, so only total distance needs minimising.","A location model should ignore minimum viable throughput, because a site's cost per unit does not depend on how much passes through it."],caselet:"Secondary delivery becomes more expensive than primary line-haul and dealers require an overnight service radius.",application:"Re-evaluate site locations using the changed cost structure, coverage limit, demand, and minimum throughput together.",applicationWrong:["Keep the existing sites, because demand locations alone determine where a stockyard belongs.","Consolidate into one large site regardless of dealer distance, since fewer sites always mean lower total network cost.","Minimise primary line-haul distance while leaving secondary delivery cost out of the comparison entirely."],bridge:"A network location changes both legs of transport and facility utilisation; service constraints turn the cheapest map into a feasible operating design."},
      {id:"sclm_coldstore",module:6,source:"SCLM-M06-L05",name:"Cold-storage expansion",summary:"Cold-storage expansion must be judged through seasonal utilisation, commodity flows, operating cost, financing, and market relationships—not capacity alone.",confusions:["A profitable existing site proves any new geography will work, because the operating model travels with the operator.","Debt structure and seasonal demand do not affect expansion risk once the facility is technically sound and well run.","Cold storage earns the same return at every utilisation level, since its costs rise and fall with the volume stored."],caselet:"An efficient operator considers a new city with different commodity flows, trader relationships, seasonal demand, and refrigerated transport needs.",application:"Test local utilisation, customer and commodity fit, operating economics, logistics, and financing before replicating the facility.",applicationWrong:["Copy the current facility exactly, because management skill transfers automatically to any market the operator enters.","Decide from the price of available land alone, treating construction cost as the whole of the expansion question.","Assume the new capacity stays full throughout the year, so a single peak-season utilisation figure can carry the case."],bridge:"An operating capability creates value only when local demand, logistics, and capital structure keep expensive capacity productively used."},
      {id:"sclm_turnaround",module:6,source:"SCLM-M06-L07",name:"Transport turnaround",summary:"Turnaround improves asset throughput by removing waiting from the full trip cycle; Rajashree targeted locomotive detention so the same rakes could make more trips.",confusions:["Throughput can rise only by buying more wagons, since the number of vehicles owned sets the ceiling on annual movement capacity.","Loading speed is the only time that matters in a rail cycle, because a rake starts earning again the moment it is full.","Idle waiting after loading does not affect annual capacity, because the wagons are already loaded and the tonnage has already been committed to a customer."],caselet:"A loaded rake waits an average 13 hours for a locomotive, limiting monthly trips despite adequate loading capacity.",application:"Coordinate an engine-on-load arrangement and accountability for the hand-off so detention falls and trips per rake rise.",applicationWrong:["Buy additional rakes before addressing the 13-hour wait, since more assets must produce more trips.","Increase factory output while loaded wagons continue to stand idle, because production volume is what limits despatch.","Measure only tonnes loaded per wagon and ignore cycle time, since a fuller wagon is always a more productive one."],bridge:"Removing non-value waiting increases the productive cycles of the same asset, linking coordination directly to capacity."},
      {id:"sclm_multimodal",module:7,source:"SCLM-M07-L06",name:"Multimodal cost trade-off",summary:"Mode choice compares end-to-end transport, handling, port, inventory, lot-size, and service effects—not freight rate alone.",confusions:["The lowest line-haul price is always the lowest total logistics cost, because freight dominates every other line.","Large sea lots never create inventory cost, since the goods are paid for only when they are sold.","Handling and first or last-mile legs can be ignored, because both modes incur them equally."],caselet:"Sea freight is far cheaper per tonne than rail but arrives in one very large annual lot and requires port, barge, and inland handling.",application:"Compare total movement cost plus inventory and handling created by the shipment size before choosing the sea option.",applicationWrong:["Choose sea immediately on the line-haul rate per tonne, since the gap against rail is too large to be reversed.","Choose rail simply because it moves smaller consignments, without costing the inventory that each shipment size creates.","Exclude port, barge, and inland handling from both options, comparing only the long-haul movement between them."],bridge:"A mode changes shipment size, time, handling, and stock as well as freight; total logistics cost joins those consequences."},
      {id:"sclm_ports",module:7,source:"SCLM-M07-L07",name:"Ports and PPP",summary:"Ports support trade and coastal movement; public-private participation can add capacity and operating capability, but performance still depends on connected infrastructure and governance.",confusions:["Port performance is determined only by whether the terminal is publicly or privately owned, and nothing else moves the number.","Container traffic can move at scale without hinterland links, because a terminal's own handling capacity sets its throughput by itself.","Private participation automatically removes every maritime constraint, so oversight of service performance can be withdrawn once the investment arrives and the equipment is installed."],caselet:"A terminal adds modern handling capacity, but road and rail evacuation remain congested and ships still face delays.",application:"Treat terminal investment, hinterland connectivity, coordination, and service performance as one port system.",applicationWrong:["Declare the port problem fixed because the cranes are newer than the ones they replaced.","Measure port capability by total national coastline length rather than by cargo actually moved.","Remove performance oversight once private investment is committed, since the operator now carries the commercial risk."],bridge:"A port is a transfer node, so capacity creates trade value only when sea-side operations and inland flows work together."},
      {id:"sclm_leads",module:8,source:"SCLM-M08-L01",name:"LEADS index",summary:"LEADS uses stakeholder perceptions and operating indicators to compare state logistics strengths and improvement areas and encourage policy competition.",confusions:["It is a direct count of warehouse square footage and nothing more, so a state improves its score by building sheds.","It ranks countries rather than Indian states and union territories, so it cannot guide state-level policy.","A high score proves every firm in the state has low logistics cost, since the index measures realised firm outcomes."],caselet:"A state ranks poorly on tracking, infrastructure, regulatory environment, and cargo safety in stakeholder surveys.",application:"Use the dimensions to target state-level policy and infrastructure improvements while recognising the measure is perception-based.",applicationWrong:["Treat the state's rank as a firm-level profit statement and plan individual company budgets from it.","Improve only warehouse capacity, because infrastructure, regulation, tracking, and cargo safety are not what the index reads.","Ignore the stakeholder evidence entirely, since perception surveys cannot indicate anything about how a state's logistics actually performs."],bridge:"A shared diagnostic makes system weaknesses visible and gives states a basis for coordinated improvement, not a guarantee of firm performance."},
      {id:"sclm_akshaya",module:8,source:"SCLM-M08-L03",name:"Akshaya Patra meal logistics",summary:"Akshaya Patra coordinates menu, mechanised production, labelled containers, route sequencing, vehicles, hygiene, and school time windows as one high-volume service system.",confusions:["Cooking volume alone determines successful meal delivery, because a kitchen that meets its target has met its obligation.","Route labels and loading sequence have no effect on service, since every container eventually holds the same meal for the same schools.","Nutritional standards can be set separately from menu and logistics design, because nutrition is decided before any vehicle is loaded."],caselet:"A central kitchen meets cooking targets, but unlabeled containers and poorly sequenced loading cause late and incorrect school deliveries.",application:"Integrate route-wise packaging, loading order, vehicle capacity, meal windows, and food-safety controls with production.",applicationWrong:["Cook more food without changing dispatch, on the view that shortfalls at school are a production problem.","Remove menu and school identifiers from containers to speed up packing at the kitchen.","Measure success only at the kitchen exit, treating everything after despatch as somebody else's responsibility."],bridge:"Public service quality is completed at the recipient, so production, routing, timing, and safety must hold together end to end."}
    ],
    synthesis:[
      {id:"sclm_syn_fit",conceptId:"sclm_drivers",source:"SCLM-M01-L06",node:"Strategy to drivers",caselet:"A retailer promises low prices and dependable availability but keeps many premium express facilities with duplicated stock.",stem:"Which diagnosis is best?",correct:"Its facilities and inventory choices may be more responsive—and costly—than the competitive promise requires, so the driver configuration lacks strategic fit.",wrong:["More facilities always improve both efficiency and responsiveness at the same time, so the network is already configured correctly for any promise.","Pricing and supply-chain choices are unrelated, because price is set in the market while cost is settled inside operations.","The only useful response is to add more product variety, since a wider range is what a low-price promise needs."],explanation:"Supply-chain drivers should deliver the promised service at the appropriate cost.",link:"Strategy becomes operational through the configuration of facilities, inventory, transport, information, sourcing, and pricing."},
      {id:"sclm_syn_forecast",conceptId:"sclm_sop",source:"SCLM-M02-L12",node:"Forecast to plan",caselet:"A forecast rises sharply, but the plant has long training times and cheap storage.",stem:"What should planning do next?",correct:"Translate the forecast into a capacity-and-inventory plan, likely using stable capacity with inventory and limited flexibility rather than blindly chasing demand.",wrong:["Use the forecast directly as the production order without checking capacity, since the forecast is what the plant has committed to deliver.","Fire and rehire workers each period regardless of training cost, because output should track demand exactly month by month.","Ignore inventory entirely, because forecasting and operations are separate functions that simply hand work to each other in sequence."],explanation:"S&OP converts forecasts into a feasible, profitable response across operational levers.",link:"A forecast has value only when its uncertainty and timing shape a feasible operating plan."},
      /* A relationship question, not a newsvendor question. Its distractors are
       * EOQ and exponential smoothing, so it tests whether the learner can tell
       * the models apart — a different failure from misapplying the right one.
       * It therefore cites every lecture it discriminates between (which gates
       * it behind all three lessons) and names the prerequisite concepts, so a
       * missed answer here can route back to the relationship rather than to
       * newsvendor alone. */
      {id:"sclm_syn_inventory",conceptId:"sclm_newsvendor",source:"SCLM-M03-L05",sourceIds:["SCLM-M03-L05","SCLM-M03-L03","SCLM-M02-L06"],supportingConceptIds:["sclm_eoq","sclm_smoothing"],node:"Choose the inventory model",caselet:"A fashion item has one buying opportunity, uncertain seasonal demand, and heavy markdowns after the season.",stem:"Which model fits best and why?",correct:"Newsvendor, because a one-time uncertain order turns on shortage and leftover costs.",wrong:["EOQ, because demand is constant across the year and replenishment orders repeat indefinitely.","Exponential smoothing alone, because updating the forecast directly chooses the profit-maximising order quantity.","A Q review model, because replenishment can occur continuously at any point after the season starts."],explanation:"Model choice follows the structure of the decision, not the fact that inventory is involved.",link:"Recurring stable replenishment and one-shot uncertain stocking require different cost logic."},
      {id:"sclm_syn_flow",conceptId:"sclm_turnaround",source:"SCLM-M06-L07",node:"Network flow",caselet:"A network adds stockyards and vehicles, yet orders remain late because loaded assets wait at every organisational hand-off.",stem:"What should be investigated first?",correct:"End-to-end cycle time and hand-off coordination, because idle detention can consume capacity despite more physical assets.",wrong:["Only the purchase price of the new vehicles, since asset cost is what the investment case turns on.","A larger safety-stock target at every node, because more stock at each point protects the delivery promise.","Removal of shared performance measures, so each site is judged only on what it controls directly."],explanation:"Waiting time can be the binding capacity constraint in a network full of assets.",link:"Network design and operating coordination meet in the time an order or asset spends between useful steps."}
    ]
  });

  catalogue.SPMS = makeCourse({
    id:"SPMS",title:"Software Product Management and Strategy",shortTitle:"SPMS",description:"How product teams choose problems, markets, business models, plans, and responsible operating decisions.",
    modules:["Product foundations","Markets and adoption","Positioning and business models","Pricing and unit economics","Competition and communication","Requirements and traceability","Priorities and roadmaps","Metrics and privacy"],
    concepts:[
      {id:"spms_dfv",module:1,source:"SPMS-M01-L05",name:"Desirability, feasibility, viability",summary:"A product opportunity must be wanted by customers, technically achievable, and economically sustainable; strength in only two dimensions leaves a predictable failure.",confusions:["Desirability means that the team can actually engineer the product to the quality standard that the market has come to expect of it.","Viability is proven whenever users say they like an idea, since stated enthusiasm eventually converts into paid revenue at scale over enough time.","A feasible and profitable concept does not need demonstrated customer demand, because the economics on paper already justify the decision to build it."],caselet:"A team can build a device and sell it at a margin, but research shows no meaningful customer problem or willingness to use it.",application:"Treat desirability as the missing test before investing further, despite feasibility and apparent unit margin.",applicationWrong:["Launch immediately, because technical feasibility is itself proof that real demand exists.","Reduce the engineering scope even though feasibility has already been established for this particular build.","Call it viable and assume customers will learn to want it once they have seen it working."],bridge:"A product survives only where customer value, engineering reality, and business economics overlap; one cannot compensate indefinitely for another."},
      {id:"spms_jtbd",module:1,source:"SPMS-M01-L10",name:"Jobs to be done",summary:"Jobs to be done focuses on the functional, emotional, and social progress a customer seeks, not merely the product category or stated feature request.",confusions:["The job is simply the list of features that customers ask developers to copy from a competing product they happen to have already seen somewhere else.","Only the functional task matters, since confidence and social context are irrelevant to whether the customer's job gets done.","A product category defines the same job for every single user, so one category description will cover everyone who sits in that whole market anyway."],caselet:"A patient asks for online consultation but mainly needs quick access to a trusted doctor and confidence that the advice is legitimate.",application:"Design around access, trust, and reassurance rather than treating video calling itself as the complete job.",applicationWrong:["Optimise only the video resolution, because that is the feature the customer actually named.","Assume every telehealth user values exactly the same outcome from the consultation they have booked.","Ignore the emotional need entirely, because anything that is not functional cannot be part of the job."],bridge:"Understanding the progress sought reveals which benefits create value and which features are only one possible means."},
      {id:"spms_tamsam",module:2,source:"SPMS-M02-L04",name:"TAM, SAM, and SOM",summary:"TAM is total theoretical demand, SAM is the portion the product and context can serve, and SOM is the realistic near-term share the firm can reach and win.",confusions:["SOM is always larger than SAM, because the obtainable market includes every single future market that the firm might eventually decide it wants to enter in future.","TAM is the set of customers that the current sales team expects to win during this quarter from its existing pipeline of qualified leads and nothing more than that.","Regulation, channel, and capability do not affect the serviceable market, since anyone who has the need is theoretically reachable by the product at some point in time."],caselet:"A regulated Indian investing app could theoretically help global investors but can currently serve Indian online retail users and initially targets cost-conscious self-directed investors.",application:"Treat global investors as TAM, Indian online retail investors as SAM, and the reachable cost-conscious segment as SOM.",applicationWrong:["Call the initial segment TAM, because that is simply the group which will be contacted first of all in the campaign.","Call all global investors SOM, because a digital product can technically reach any one of them anywhere in the world.","Ignore regulation entirely when defining SAM, since rules do not change who could theoretically buy."],bridge:"Market sizing becomes actionable by narrowing theoretical need through service constraints to the customers the current product can actually win."},
      {id:"spms_chasm",module:2,source:"SPMS-M02-L10",name:"Crossing the chasm",summary:"Moving from early adopters to mainstream customers requires a focused beachhead, complete and reliable experience, references, support, integration, and lower adoption risk.",confusions:["Mainstream adoption follows automatically once innovators approve, because the early verdict carries across to the whole market.","The best strategy is to broaden to every segment at once, before building any references or support structure at all.","Mainstream users tolerate more risk and missing support than early adopters do, since they arrive later and therefore expect a good deal less."],caselet:"A new enterprise tool delights technical pioneers but mainstream buyers ask for uptime, integration, references, security, and support.",application:"Win a narrow beachhead with a complete, credible solution and use its references before expanding.",applicationWrong:["Add more experimental features aimed at every possible segment at the same time.","Dismiss the reliability concerns as ordinary resistance to innovation coming from the more conservative buyers.","Target the whole market at once, before proving that even one repeatable use case works reliably."],bridge:"Early enthusiasm proves possibility; mainstream adoption depends on reducing the practical and social risk of switching."},
      {id:"spms_positioning",module:3,source:"SPMS-M03-L02",name:"Product definition and positioning",summary:"Product definition clarifies what is being built and the problem it solves, while positioning explains the differentiated value to a target customer relative to alternatives.",confusions:["A positioning statement is really an internal technical specification, written for the engineering team to build the product from during the development phase itself.","Product definition and positioning are identical feature lists, simply written out twice over for two different internal audiences to read and then approve before launch.","Positioning does not require naming either a target user or the alternative the product is being compared against by the buyer at the time of purchase."],caselet:"A team describes its payment product only as 'an API with new database tables' when speaking to small merchants.",application:"Translate the internal definition into customer positioning: who it serves, the payment problem solved, the benefit, and why it differs from alternatives.",applicationWrong:["Add more implementation detail into the customer message so the buyer understands exactly how the thing works.","Remove the target segment from the statement so that everyone who reads it feels included in what the product offers.","List the product's features on their own, without ever stating the customer outcome those features are supposed to produce."],bridge:"Definition aligns builders on the solution; positioning helps a chosen customer understand why that solution matters and is different."},
      {id:"spms_lean_canvas",module:3,source:"SPMS-M03-L06",name:"Lean Canvas",summary:"Lean Canvas adapts one-page business modelling for early-stage uncertainty by emphasising problem, solution, key metrics, and unfair advantage.",confusions:["It is used only to document a mature company's fixed operating model once that model has settled.","It removes customer segments and channels from business modelling to keep the single page simple enough to read.","Its purpose is to finalise every assumption before any testing begins with real customers at all."],caselet:"An early startup needs to decide whether a problem is worth solving and which assumptions an MVP should test.",application:"Use Lean Canvas to expose problem, solution, metrics, advantage, segments, channels, costs, and revenue as testable assumptions.",applicationWrong:["Use it as a final audited financial statement for the board to sign off.","Fill only the solution box and treat the rest as execution detail.","Avoid revising the canvas once evidence arrives, since the original plan should be allowed to hold."],bridge:"A compact model makes linked business assumptions visible so learning can change the whole system rather than one feature at a time."},
      {id:"spms_value_pricing",module:4,source:"SPMS-M04-L02",name:"Value-based pricing",summary:"Value-based pricing starts from measurable customer value and segment-specific willingness to pay, then designs the offering and price structure around that value.",confusions:["Price should always equal unit cost plus a fixed markup, whatever the customer actually gains from using it.","All customer segments receive the same value from the product and should therefore be charged an identical price for it.","Value can be priced without ever being articulated or measured, since the customer already knows what it is worth to them anyway."],caselet:"Software saves one segment ₹10 lakh a year but saves another only ₹50,000, while serving both costs roughly the same.",application:"Use the different economic value and willingness to pay to shape segment-specific offers and price structure.",applicationWrong:["Charge both segments from an identical delivery cost, since the software is the same.","Set the price from the cheaper alternative's feature count alone.","Ignore the measurable savings the customer gains, because software has a low marginal cost."],bridge:"Pricing captures part of created value; clear segmentation and value evidence connect customer benefit to business viability."},
      {id:"spms_unit_economics",module:4,source:"SPMS-M04-L07",name:"Unit economics",summary:"Unit economics tests profitability at the relevant customer or transaction level using measures such as acquisition cost, gross contribution, lifetime value, churn, and payback.",confusions:["Rapid revenue growth proves healthy unit economics automatically, because a fast-growing top line eventually covers everything underneath it in the end.","CAC should be compared with total revenue rather than gross contribution, because revenue is the number the customer actually pays each month.","A long payback period cannot create any cash-flow risk, as long as the lifetime value is high enough to cover it eventually."],caselet:"A subscription spends ₹1,000 to acquire a customer and earns ₹100 monthly gross profit from that customer.",application:"Recognise a ten-month CAC payback before considering retention, cash burn, and whether lifetime gross profit comfortably exceeds acquisition cost.",applicationWrong:["Call the payback period one month, because the subscription happens to bill on a monthly cycle to the customer each time.","Compare CAC only with the top-line company revenue and stop the analysis there without looking at contribution.","Ignore churn entirely, because the acquisition has already happened and that cost is already sunk anyway."],bridge:"Growth consumes cash before contribution repays acquisition; per-unit economics shows whether scaling improves or deepens the problem."},
      {id:"spms_alternatives",module:5,source:"SPMS-M05-L02",name:"Competition and alternatives",summary:"Competition includes every current or potential way customers accomplish the job, including substitutes and doing nothing—not only similar products.",confusions:["Only firms shipping the same feature list should be counted as competitors in this particular market.","Customers cannot compare a product against manual work or against simply doing nothing at all about the problem.","Competition should be defined first, before anyone works out the customer's underlying job."],caselet:"A collaboration app compares itself only with two other apps, while prospects continue using email, spreadsheets, meetings, or no formal system.",application:"Evaluate those behaviours as alternatives because they compete for the same customer progress and switching decision.",applicationWrong:["Ignore them entirely because they are not software products competing in the category.","Study only the companies building on the same technology stack as this product does today.","Assume customers will abandon their current workflows as soon as they see a longer feature list somewhere."],bridge:"The customer's job defines the competitive field; positioning improves when the product beats the real behaviour it must replace."},
      {id:"spms_buyer_journey",module:5,source:"SPMS-M05-L04",name:"Buyer journey communication",summary:"Value communication should match the buyer's stage—from unawareness through consideration and decision—with the need, evidence, format, and channel useful at that moment.",confusions:["One feature-heavy message should simply be repeated at every stage of the buyer's journey without change.","Communication begins only after the customer has already purchased, since that is the point at which real support actually starts.","Channel and evidence do not need to match the buyer's questions, because message beats medium."],caselet:"Potential users do not yet recognise a health-monitoring problem, but the campaign opens with a detailed comparison of advanced settings.",application:"First make the problem and relevant value understandable, then introduce alternatives and proof as the buyer advances.",applicationWrong:["Add more technical detail into the very first message the buyer ever receives.","Wait until after the purchase is complete before explaining any of the value to the customer.","Use the same decision-stage proof on audiences who are not yet aware that the problem exists at all."],bridge:"Customers need different information before they can take each next step; timing turns product value into understandable evidence."},
      {id:"spms_requirements",module:6,source:"SPMS-M06-L05",name:"Functional and quality requirements",summary:"Functional requirements state what the product must do; quality or non-functional requirements state how well or under what constraints it must do it.",confusions:["Security and performance are always optional feature requests that can be added later on if there is time.","A functional requirement describes only the colour and layout of the user interface as it finally appears on the screen.","Quality requirements do not need measurable conditions attached to them, since their general intent is already understood by everyone on the team."],caselet:"A login system must authenticate users and block unauthorised access within a defined response time.",application:"Treat authentication as functional, and security and response-time conditions as quality requirements that constrain its implementation.",applicationWrong:["Treat every statement in the list as the same kind of feature label.","Omit the security condition because a login screen already exists somewhere in the product today.","Record response time only after release, not as a requirement."],bridge:"A capability is incomplete without the quality conditions that make it safe, usable, and compliant in the real product."},
      {id:"spms_traceability",module:6,source:"SPMS-M06-L08",name:"Requirements traceability",summary:"Traceability links a customer need through product requirements, implementation, and verification so scope and change decisions remain explainable.",confusions:["Traceability is only a list of developer tasks kept inside the team's project tracking tool.","Once a requirement is written down, its original source and its tests can safely be discarded from the record.","Customer requirements and project requirements should never be connected to one another anywhere in the documentation."],caselet:"A team cannot explain which user need a database field supports or which test proves the related requirement works.",application:"Create links from the originating need to the product requirement, implementation item, and verification evidence.",applicationWrong:["Keep each artifact in a separate, unlinked document with no reference between them.","Delete the original customer source once development work has actually started on that requirement.","Approve the field because something like it already exists in code."],bridge:"Traceability preserves the reason behind work, making change impact and completion evidence visible across the development chain."},
      {id:"spms_priority",module:7,source:"SPMS-M07-L01",name:"MoSCoW and RICE prioritisation",summary:"MoSCoW aligns necessity categories, while RICE compares reach, impact, confidence, and effort; both make trade-offs explicit rather than replacing judgement.",confusions:["Every stakeholder request should be marked a Must have so that nobody involved is left disappointed.","RICE ignores effort and confidence entirely, and ranks competing ideas on reach and impact alone when scoring them.","A numeric score eliminates the need to examine the assumptions that produced that number in the first place anyway."],caselet:"Two features differ in user reach, likely impact, evidence confidence, and engineering effort, while a legal capability is non-negotiable.",application:"Mark the legal capability as Must and use a transparent RICE comparison for discretionary features, then review assumptions.",applicationWrong:["Put all three items into the Must have category so that no conflict arises between the stakeholders.","Choose the idea with the highest claimed impact and ignore the confidence and effort scores entirely when ranking them.","Let the loudest stakeholder in the room set the order of the whole backlog each time."],bridge:"Prioritisation turns scarce capacity into an explicit decision by separating necessity from comparative value and evidence."},
      {id:"spms_roadmap",module:7,source:"SPMS-M07-L04",name:"Product roadmap",summary:"A roadmap translates product strategy into an adaptable sequence of outcomes and releases over time, with more detail and confidence near term than far term.",confusions:["A roadmap is an unchangeable promise of exactly which features will ship, and on exactly which dates, for years into the future.","It is identical to the current sprint backlog, simply written out in a different format for a different audience each quarter.","Market and technology change should not affect the roadmap, because a plan that keeps moving is not a plan."],caselet:"A team publishes exact five-year feature dates although technology, regulation, and customer evidence are changing quickly.",application:"Keep the strategic direction and outcome sequence, but express distant work with lower detail and update it as evidence changes.",applicationWrong:["Freeze every feature date in place in order to protect the credibility of the originally published plan.","Remove the long-term direction altogether and keep only the tasks that the team happens to be working on right now.","Treat the roadmap as a sales contract carrying no uncertainty at all for the customer who has signed it."],bridge:"A roadmap gives direction without pretending distant uncertainty is resolved; learning should reshape the route while strategy anchors it."},
      {id:"spms_metrics",module:8,source:"SPMS-M08-L03",name:"Actionable product metrics",summary:"Useful product metrics reduce uncertainty and guide a decision across business, product, customer, or marketing performance; impressive totals without a decision are vanity metrics.",confusions:["The largest available number is always the best metric to report, because sheer scale is what demonstrates real progress.","Early-stage products need only the profit measures that a mature company would report to its own board each year.","A metric remains useful even when no action anyone could take would ever change as a result of what that metric reports back."],caselet:"A startup celebrates total registrations while activation, repeat use, churn, acquisition cost, and cash risk remain unclear.",application:"Choose stage-relevant measures tied to decisions, such as activation, retention, contribution, and acquisition payback.",applicationWrong:["Increase the font size of the registration number shown on the dashboard.","Track every possible number without assigning owners or attaching decisions to any single one of them.","Wait for a mature profit history to build up before measuring any product behaviour at all."],bridge:"A metric earns its place when evidence can change resource allocation, product action, or risk response."},
      {id:"spms_privacy",module:8,source:"SPMS-M08-L05",name:"Privacy by design",summary:"Privacy by design makes lawful purpose, consent, minimisation, protection, user rights, and compliant partners part of the product from the start.",confusions:["Privacy is simply a notice added to the site once the data collection is already complete.","A firm can ignore its partners' data practices entirely once the processing work has been outsourced to them.","All personal data may be reused for any new purpose whenever it improves a feature."],caselet:"An app collects broad personal data for an undefined future use and sends it to an unreviewed analytics vendor.",application:"Limit collection to a stated purpose, establish the lawful basis and user controls, protect the data, and verify the vendor's compliance before transfer.",applicationWrong:["Collect everything available now and decide what the stated purpose for it will be at some later point.","Treat the act of outsourcing as a complete transfer of legal responsibility to the vendor who now holds and processes the data on its behalf.","Rely only on a long terms-of-service page that is published after the collection has already happened on the site."],bridge:"Data value does not remove accountability; product architecture determines whether privacy obligations can actually be honoured."}
    ],
    synthesis:[
      {id:"spms_syn_discovery",conceptId:"spms_jtbd",source:"SPMS-M01-L10",node:"Need to market",caselet:"A team has a technically feasible product for a huge TAM but cannot name the customer progress it improves.",stem:"What should happen before scaling?",correct:"Return to the customer job and desirability evidence, then narrow to a reachable segment whose unmet progress the product can serve.",wrong:["Increase the TAM estimates until the business case finally works on the spreadsheet in front of you.","Add more features to the product, because demonstrated technical feasibility is itself proof of real customer value here.","Set a price for the product before identifying what customer outcome it is actually meant to deliver for anyone who buys it."],explanation:"Market size and technical ability cannot replace a clear customer job and desirability evidence.",link:"Discovery connects the job, the desired value, and the first serviceable market before scale."},
      {id:"spms_syn_model",conceptId:"spms_unit_economics",source:"SPMS-M04-L07",node:"Value to economics",caselet:"Customers report high value and accept the price, but acquisition payback is longer than typical retention.",stem:"What does the evidence imply?",correct:"The offer may create value, but its acquisition or retention economics must change before growth is sustainable.",wrong:["High willingness to pay proves the whole business model is viable on its own.","Increase acquisition spending further, because every additional signup adds revenue straight to the top line each month it renews.","Ignore retention entirely when calculating lifetime value, since that customer has already been won and counted."],explanation:"Customer value and unit economics are separate necessary links in viability.",link:"Pricing captures value, but retention and contribution determine whether acquisition can be repaid."},
      {id:"spms_syn_plan",conceptId:"spms_roadmap",source:"SPMS-M07-L04",node:"Evidence to roadmap",caselet:"A new privacy requirement invalidates a planned data feature, but the roadmap still shows it as committed.",stem:"What is the responsible product response?",correct:"Trace the affected requirement, revise priorities and the roadmap, and communicate how the strategic outcome will be met safely.",wrong:["Build it unchanged, because a published roadmap cannot be moved once it has been committed to publicly.","Delete the privacy requirement from the backlog entirely so that the original delivery date can still be held as promised.","Hide the change from the stakeholders until after the release has already gone out to customers in production."],explanation:"Traceability and an adaptable roadmap let new evidence change delivery without losing strategic direction.",link:"A plan is credible when requirements, priorities, risks, and communication change together."},
      {id:"spms_syn_responsible",conceptId:"spms_privacy",source:"SPMS-M08-L05",node:"Metrics and responsibility",caselet:"A recommendation feature increases engagement but uses sensitive data outside the purpose users accepted.",stem:"Which decision best joins performance and responsibility?",correct:"Stop or redesign the data use, preserve purpose and consent, and measure whether a compliant alternative still delivers customer value.",wrong:["Keep it running, because engagement is the highest product metric the team currently reports to the board.","Update the privacy notice on the site while continuing exactly the same processing underneath it as before the change was made.","Remove the engagement metric from the dashboard altogether so that the issue simply appears to disappear from view."],explanation:"A performance improvement does not override privacy obligations or user trust.",link:"Responsible product management treats legal and human constraints as part of product value, not as external paperwork."}
    ]
  });

  window.T6_COURSES = catalogue;
})();
