/* Integrated applied scenarios.
 *
 * The rest of the written bank asks a learner to explain one named concept.
 * The papers do not work that way. BRGSA Section C is two ten-mark written
 * answers, and the whole IBM paper is ten ten-mark answers on a single caselet
 * released two days beforehand. Both describe a situation and leave the
 * candidate to work out which frameworks it calls for.
 *
 * The course's own class tests frame every question the same way: a situation
 * carrying real figures, then "what is the most defensible interpretation",
 * with the concept never named in the stem. These scenarios follow that
 * register at the length a ten-mark answer needs, and each one deliberately
 * spans several modules, because recognising which ideas apply — and which of
 * them is doing the real work — is the skill being examined.
 *
 * Three rules hold for every scenario here:
 *
 *   The stem never names the concept. A stem that says "apply the growth
 *   constraint" has already answered the first and hardest part.
 *
 *   Every figure in the caselet is load-bearing. The evidence criterion asks
 *   the learner to cite one, so a scenario padded with decorative numbers
 *   teaches them to quote whichever is nearest.
 *
 *   The exemplar is written out in full rather than assembled from concept
 *   fields. Assembling it is what previously produced model answers whose last
 *   sentence did not follow from the question.
 *
 * `conceptIds` drives both the evidence boundary and repair routing: the
 * question is marked only against those concepts' lectures, and a missed
 * criterion can send the learner back to the specific idea they dropped.
 */
(function () {
  "use strict";

  var SCENARIOS = {
    BRGSA: [
      {
        id: "brgsa_case_scale_decision",
        module: 3,
        title: "The board wants to double acquisition spend",
        conceptIds: ["brgsa_m3_cohort", "brgsa_m3_economics", "brgsa_m4_constraint", "brgsa_m8_decision"],
        caselet: "Clairo has grown total active accounts from 4,100 to 8,400 in nine months, and the board has approved doubling acquisition spend next quarter on that basis. The growth lead pulls the numbers apart before the money is committed. Blended CAC has risen from ₹1,900 to ₹3,400. Month-3 retention by signup cohort has fallen every month for six months, from 31% to 22%. Split by segment, accounts that reach the team plan return roughly five times their acquisition cost, while single-seat accounts return about 1.1 times. Activation — the share of signups completing their first recorded meeting — has sat between 33% and 35% throughout, against a 50% benchmark. The dashboard the board reviews shows total accounts, weekly signups and website visits. None of the three has an owner or a stated threshold.",
        task: "The board meets in a week. Write the case the growth lead should make: what the numbers actually show, what should happen to the spending decision, and what has to change before scale is defensible.",
        rubric: [
          {id: "diagnosis", label: "Governing ideas", description: "Identifies the ideas this situation calls for without being told them: cohort retention read at equal age rather than in aggregate, segment-level CAC against LTV, a single binding constraint, and metrics that carry owners and thresholds."},
          {id: "evidence", label: "Use of the numbers", description: "Cites specific figures from the case — the cohort fall from 31% to 22%, CAC from ₹1,900 to ₹3,400, the roughly five-to-one against 1.1-to-one segment split, or activation held at 33–35% against the 50% benchmark — rather than describing the situation generally."},
          {id: "integration", label: "How the ideas connect", description: "Explains the causal chain rather than listing findings: acquisition is refilling a leaking bucket, the leak is located at activation, and the economics only work in one segment, so more spend multiplies the loss."},
          {id: "decision", label: "The decision", description: "States clearly that the spend increase should be held, names activation as the constraint to fix first, and identifies the team-plan segment as the one worth acquiring."},
          {id: "limit", label: "What would change it", description: "Names what would make scaling defensible — activation moving toward the benchmark, cohort curves flattening, or the segment ratio holding — or states the cost and risk of holding the spend."}
        ],
        exemplar: "The board is reading an aggregate that hides the thing that matters. Total accounts rose from 4,100 to 8,400, but month-3 retention by signup cohort fell from 31% to 22% across six consecutive cohorts, which means each new group is worth less than the one before it. Aggregate growth of this shape is acquisition refilling a leaking bucket. The funnel locates the leak: activation has been stuck between 33% and 35% against a 50% benchmark while every other stage moved, so activation is the binding constraint, and spend applied anywhere else will not move the end-to-end outcome. The economics say the same thing from the other side. Blended CAC has risen from ₹1,900 to ₹3,400, but the blend conceals a split — team-plan accounts return about five times acquisition cost while single-seat accounts return about 1.1, which is barely viable. Doubling spend at the current activation rate buys more single-seat accounts that leak out before they repay. The recommendation is to hold the increase, fix the activation step first, and redirect acquisition toward the team-plan segment. The dashboard has to change too: total accounts, signups and visits have no owner and no threshold, so nothing on it can trigger a decision. Scaling becomes defensible when activation moves toward the benchmark and cohort curves stop falling; if they do, the same spend buys a customer who repays."
      },
      {
        id: "brgsa_case_false_win",
        module: 2,
        title: "The test everyone believed",
        conceptIds: ["brgsa_m1_evidence", "brgsa_m2_design", "brgsa_m2_error", "brgsa_m8_priority"],
        caselet: "Zoko's team tested a new starter-kit call to action. Traffic is heavy enough that the pre-calculated sample of 9,000 sessions per variant would be reached in about seven days, covering a full week. On day three the dashboard showed the variant 9 percentage points ahead, and the team shipped it that afternoon. Two months on, the conversion rate sits where it was before the change. The team's confidence in the original idea had been scored 9 out of 10 in planning, on the strength of everyone in the room agreeing it would work; the supporting evidence recorded was a set of customer interviews in which 34 of 40 respondents said they would prefer the new wording. The team now has 40 further experiment ideas and capacity for 6 this quarter, and is proposing to re-run the same test with a larger creative budget.",
        task: "Write the review of what went wrong and what the team should do next quarter. Be specific about which failure is which, and do not let the proposal to re-run the test pass unexamined.",
        rubric: [
          {id: "diagnosis", label: "Governing ideas", description: "Identifies stopping before the pre-set sample as peeking that inflates the false-positive rate, names the resulting Type I error, and recognises that stated interview preference is a weak evidence class and cannot support a confidence score of 9."},
          {id: "evidence", label: "Use of the numbers", description: "Cites specific figures — the day-three stop against a 9,000-per-variant sample reached in seven days, the 9-point lead that did not survive, the confidence score of 9 on 34 of 40 stated preferences, or 40 ideas against capacity for 6."},
          {id: "integration", label: "How the ideas connect", description: "Connects the failures rather than listing them: weak evidence inflated confidence, which made the team eager to believe an early reading, and stopping early converted that eagerness into a shipped false positive."},
          {id: "decision", label: "The decision", description: "States what should happen next: run to the pre-declared sample, cap confidence where evidence is only stated preference, and score the 40 ideas against the current constraint before choosing 6."},
          {id: "limit", label: "What would change it", description: "Names what evidence would justify re-running the test, or acknowledges the cost of the discipline — a full week per test against capacity for six experiments."}
        ],
        exemplar: "Two separate failures compounded here, and the proposal to re-run the test repeats both. The first is a decision error. The sample was calculated at 9,000 sessions per variant and would have been reached in about seven days; the team stopped on day three on a 9-point lead. Checking before the planned sample is peeking, and stopping because the preferred result appeared inflates the false-positive rate. The effect did not survive contact with two months of real traffic, which is what a Type I error looks like from the outside: the team scaled something that was not there. The second failure is upstream, in how the idea earned its place. Confidence was scored 9 out of 10 because the room agreed, supported by 34 of 40 respondents saying they would prefer the new wording. Stated preference sits near the weak end of the evidence spectrum because it costs the respondent nothing, and a confidence score should cap at five when the evidence behind it cannot be named as anything stronger. An inflated confidence score is what made an early favourable reading feel like confirmation rather than noise. Next quarter the team should run tests to the declared sample with the stopping rule fixed in advance, score its 40 ideas against the current growth constraint rather than enthusiasm, and pick the 6 that attack it. Re-running the same test with a larger creative budget is only defensible if the idea still ranks after honest rescoring — a bigger budget does not repair a test that was never allowed to finish."
      },
      {
        id: "brgsa_case_hollow_growth",
        module: 6,
        title: "The spike that did not stay",
        conceptIds: ["brgsa_m5_activation", "brgsa_m6_habit", "brgsa_m6_churn", "brgsa_m5_channel"],
        caselet: "A consumer skincare brand ran a referral offer giving both parties ₹300 off. Signups rose from about 900 a week to 3,600 during the four-week promotion, and the founder has told investors the product has a network effect. Since the promotion ended, weekly signups have settled at 1,050. Of the referred customers, 71% never placed a second order. Onboarding for a first-time buyer runs to nine steps before the first delivery is confirmed, including account creation, a skin questionnaire and a routine-builder quiz. Repeat customers who complete a second order within 21 days go on to retain at four times the rate of those who do not. Asked whether the product became more useful to them as more people joined, existing customers said it made no difference. The brand is now considering moving most of its budget into a paid channel whose customers historically retain poorly.",
        task: "Write the assessment the founder should have before repeating this. Address the claim made to investors directly, and say what the brand should do instead.",
        rubric: [
          {id: "diagnosis", label: "Governing ideas", description: "Applies the joining test to reject the network-effect claim and identify a referral incentive, locates the loss at activation before first value, and recognises the 21-day second order as the habit the lifecycle should be built around."},
          {id: "evidence", label: "Use of the numbers", description: "Cites specific figures — 900 to 3,600 and back to 1,050, 71% never reordering, nine onboarding steps, the four-times retention for a second order inside 21 days, or existing customers reporting no change in value."},
          {id: "integration", label: "How the ideas connect", description: "Connects them rather than listing: the incentive bought arrivals, the onboarding path lost them before first value, and with no repeat behaviour established there was never a loop for a network effect to sit on."},
          {id: "decision", label: "The decision", description: "States that the network-effect claim should be withdrawn, that onboarding friction ahead of first value should be cut, and that the second order inside 21 days should become the activation target before more spend is committed."},
          {id: "limit", label: "What would change it", description: "Names what would justify the paid channel or a repeat promotion — activation and second-order rates holding first — or states what the correction costs in short-term signup volume."}
        ],
        exemplar: "The claim made to investors does not survive the test the course sets. A network effect means an additional user makes the product more valuable to those already there; asked exactly that, existing customers said it made no difference. What the promotion built was a referral incentive: it brought arrivals and stopped bringing them when the money stopped, which is why weekly signups went from about 900 to 3,600 and settled at 1,050. That claim should be withdrawn before it is repeated. The more useful finding is where those arrivals went. Of the referred customers, 71% never placed a second order, and the path to a first delivery runs nine steps including a skin questionnaire and a routine-builder quiz. Each of those steps applies to whoever is left, so a chain of individually reasonable steps can destroy activation without any single one looking like the culprit. The brand paid ₹300 twice over to push people into a funnel that loses most of them before the product has done anything for them. The case also contains the habit worth building around: customers who place a second order within 21 days retain at four times the rate of those who do not, which makes that the activation event and the thing lifecycle messaging should be timed to produce. The sequence is to cut the pre-value steps, define activation as the second order inside 21 days, and only then spend on acquisition. Moving budget into a channel whose customers historically retain poorly repeats the same error at higher cost: it buys more arrivals into an unfixed leak. If activation and second-order rates hold after the repair, the channel question becomes worth asking on its economics."
      },
      {
        id: "brgsa_case_revenue_engine",
        module: 7,
        title: "Revenue that grows while the base shrinks",
        conceptIds: ["brgsa_m7_pricing", "brgsa_m7_pipeline", "brgsa_m4_customers"],
        caselet: "A B2B company reports recurring revenue up 18% year on year and is preparing to hire a performance marketer, a demand-generation manager and an attribution stack. Its cohort numbers tell a different story: of ₹20 lakh of monthly recurring revenue held by customers twelve months ago, ₹16 lakh remains, with expansion of ₹2 lakh offset by ₹4 lakh of churn and ₹2 lakh of downgrades. The headline growth comes from new logos. Pricing is a single flat plan at ₹1,500 per seat with no upgrade path. Marketing recorded 100 qualified leads last quarter; sales accepted 75 and disputes the definition of the other 25, which was never agreed between them. Average time from a lead arriving to first contact is four days. The founder is still personally closing the largest accounts and has never handed that motion to anyone.",
        task: "Write the recommendation on where this company should spend its next quarter. The hiring plan is already drafted, so say plainly whether it should proceed.",
        rubric: [
          {id: "diagnosis", label: "Governing ideas", description: "Computes or recognises net revenue retention on the existing base, identifies the flat plan as a structure with no expansion path, names the undefined marketing-to-sales handoff and response time as the leak, and places the company on the ladder of proof rather than at scale stage."},
          {id: "evidence", label: "Use of the numbers", description: "Cites specific figures — ₹16 lakh remaining of ₹20 lakh, or 80% NRR, the flat ₹1,500 seat price with no upgrade path, 100 leads against 75 accepted, four days to first contact, or the founder still closing the largest accounts."},
          {id: "integration", label: "How the ideas connect", description: "Connects them: new logos are masking a base that is shrinking, the pricing structure gives retained customers no way to expand, and the handoff loses qualified demand before the motion is repeatable enough to hire against."},
          {id: "decision", label: "The decision", description: "States that the hiring plan should not proceed as drafted, and names what to do first — repair the handoff definition and SLA, and redesign pricing so expansion is possible."},
          {id: "limit", label: "What would change it", description: "Names what would make the scale-stage hires right — a repeatable motion, NRR above 100%, an agreed handoff — or states what delaying the hires costs."}
        ],
        exemplar: "The hiring plan should not proceed as drafted, because it is a scale-stage playbook bought for a company that has not finished the search. Start with the base. Of ₹20 lakh of recurring revenue held twelve months ago, ₹16 lakh remains: ₹2 lakh of expansion against ₹4 lakh of churn and ₹2 lakh of downgrades, which is net revenue retention of 80%. Headline growth of 18% is new logos being poured over a base that is shrinking underneath them, and hiring three people to pour faster does not change the direction of that number. Part of the reason sits in the pricing. A single flat plan at ₹1,500 per seat gives a satisfied customer no route to spend more, so the structure itself has no expansion path and every rupee of growth has to be won again from someone new. Pricing here is not a number to adjust but a structure to redesign, and it is the cheapest lever available because expansion revenue costs no acquisition. The second reason is the handoff. Marketing recorded 100 qualified leads and sales accepted 75, with the definition of the disputed 25 never agreed between them, and first contact takes four days. Demand is being lost in the transition rather than at either end, and no attribution stack will show that, because each team's own numbers look fine. Meanwhile the founder is still closing the largest accounts personally, which is the signature of a motion that is not yet repeatable — the rung before the one the hiring plan assumes. The next quarter should go on defining the handoff criteria, context and response time, and on rebuilding pricing so accounts can expand. The hires become the right call once NRR is above 100% and the closing motion has been handed off successfully at least once; until then they add cost to a leak."
      }
    ],
    IBM: [
      {
        id: "ibm_case_hospital_growth",
        module: 2,
        title: "Where the next hospital should go",
        conceptIds: ["ibm_vaatsalya", "ibm_aravind", "ibm_impact_measurement"],
        caselet: "A hospital group runs six 200-bed tertiary facilities in three large cities, with cardiac and oncology units at 61% occupancy. Its records show 44% of admissions travel more than 90 km, most for deliveries, dialysis and routine surgery requiring no tertiary equipment; a normal delivery costs such a patient about ₹38,000 including travel and lost wages. A proposal would open twelve 40-bed centres in semi-urban towns handling primary and secondary care only, at roughly ₹11,000 per delivery. Separately, the group's four surgeons each spend about 70% of their working day on counselling, measurement and post-operative dressing, with a nine-week waiting list; 22 trained paramedical staff are assigned mostly to reception. The group's impact report states that patients treated at its facilities earn more two years later than those who were not, and the board is citing this to justify expansion.",
        task: "Advise the board. Address the expansion proposal, the capacity problem inside the existing hospitals, and the evidence the report is resting on.",
        rubric: [
          {id: "diagnosis", label: "Governing ideas", description: "Identifies locating focused secondary capacity near the underserved population, separating standardisable work from the scarce specialist to raise throughput, and the absence of a counterfactual in the impact claim."},
          {id: "evidence", label: "Use of the numbers", description: "Cites specific figures — 44% travelling over 90 km, ₹38,000 against ₹11,000 per delivery, 61% occupancy in tertiary units, 70% of surgeon time on non-surgical work, the nine-week list, or the 22 paramedical staff on reception."},
          {id: "integration", label: "How the ideas connect", description: "Connects them: the access problem and the capacity problem are separate constraints with separate fixes, and neither is evidenced by the earnings claim as it stands."},
          {id: "decision", label: "The decision", description: "Supports the semi-urban secondary network for the routine load, recommends redistributing non-surgical tasks to the existing paramedical staff, and declines to rest expansion on the current impact claim."},
          {id: "limit", label: "What would change it", description: "Names what evidence would support the impact claim — a comparison group similar before treatment — or the conditions under which the cost discipline would start to threaten essential quality."}
        ],
        exemplar: "There are three separate questions here and the board is currently answering all of them with one number. On location, the case for the semi-urban network is strong. Forty-four per cent of admissions travel more than 90 km for deliveries, dialysis and routine surgery that need no tertiary equipment, and that journey costs a patient about ₹38,000 against roughly ₹11,000 at a 40-bed secondary centre. Where care sits determines who can reach it, and placing focused secondary capacity near those patients removes a burden that no efficiency inside the city hospitals can touch. The tertiary units running at 61% occupancy confirm the mismatch: expensive capacity is idle while the wrong patients travel to it. On capacity, the constraint inside the existing hospitals is not the number of surgeons. Four surgeons spend around 70% of the working day on counselling, measurement and post-operative dressing while 22 trained paramedical staff sit mostly at reception, and there is a nine-week waiting list. Separating the standardisable work from the scarce specialist raises surgical throughput without recruiting anyone, provided the clinical quality that justifies the whole model is monitored and holds. On evidence, the impact claim should not carry the expansion decision. Patients treated at the group's facilities earning more two years later tells us about people who reached those facilities, who may differ from those who did not in exactly the ways that also affect earnings. Without a comparison group similar before treatment, the figure cannot separate what the hospitals caused from who chose to attend. The board should approve the secondary network on the access and cost evidence, redistribute the non-surgical tasks, and commission a proper counterfactual before repeating the earnings claim to funders."
      },
      {
        id: "ibm_case_lender_pressure",
        module: 3,
        title: "A portfolio that looks healthy",
        conceptIds: ["ibm_grameen", "ibm_responsible_lending", "ibm_impact_investing"],
        caselet: "A microfinance institution has grown disbursements 140% in two years and reports portfolio-at-risk of 1.2%. Field agents earn 60% of variable pay per additional loan disbursed, with nothing tied to repayment. A sample of 500 borrowers finds the median household servicing four concurrent microloans, 38% having used their most recent loan to repay an existing one, and total debt service at 71% of reported household income. In the institution's original districts, lending ran through self-formed groups of five with staged disbursement and weekly village meetings, and repayment held at 97% over eighteen months; in the new districts the group label was kept but the meetings and staged release were dropped to lower cost per loan. An impact fund is preparing to invest, expects a 9% return, and has asked what the institution measures beyond disbursement volume.",
        task: "Write the assessment the impact fund's investment committee needs before it commits. State whether the institution should keep growing at its current rate.",
        rubric: [
          {id: "diagnosis", label: "Governing ideas", description: "Identifies that repayment capacity, not disbursement volume, is the test of responsible lending; recognises staged release and group meetings as the screening mechanism rather than administrative overhead; and separates intent, measurement and return in the fund's decision."},
          {id: "evidence", label: "Use of the numbers", description: "Cites specific figures — 1.2% portfolio-at-risk against 38% refinancing, debt service at 71% of income, four concurrent loans, 60% of agent pay per disbursement, or 97% repayment where the meetings and staged release were kept."},
          {id: "integration", label: "How the ideas connect", description: "Connects them: the incentive drives volume, the dropped screening mechanism removed the check on capacity, and refinancing keeps accounts current so the headline risk figure conceals the problem it is supposed to reveal."},
          {id: "decision", label: "The decision", description: "States that growth should pause pending an assessment of total household obligations, that agent incentives must be re-tied to repayment, and that the screening mechanism should be restored in the new districts."},
          {id: "limit", label: "What would change it", description: "Names what the fund should require before investing — capacity-based measurement, restored screening, evidence the 9% return does not depend on continued refinancing — or what the pause costs."}
        ],
        exemplar: "The portfolio-at-risk figure is the least informative number in this case. It reads 1.2% because 38% of sampled borrowers used their most recent loan to repay an existing one, and refinancing keeps accounts current whether or not the household can afford them. The number that matters is debt service at 71% of reported income across a median of four concurrent loans, which is not access to credit but a household being lent past its capacity. Responsible lending tests total obligations and repayment capacity rather than rewarding volume, and on that test this portfolio is deteriorating while its headline metric improves. The cause is visible in two design choices. Field agents earn 60% of variable pay per additional loan disbursed with nothing tied to repayment, so the incentive is pointed squarely at the behaviour producing the harm. And in the new districts the group label was kept while the staged disbursement and weekly meetings were dropped. Those were not overhead: releasing funds to two members first and meeting weekly is how local knowledge entered the credit assessment at all, and it is why the original districts held 97% repayment over eighteen months. Removing the mechanism and keeping the name removed the screening while preserving the appearance of it. The institution should pause new lending in the affected districts, assess total household obligations rather than its own exposure, re-tie agent pay to repayment, and restore staged release and meetings before growing further. For the fund, intent and return are not enough on their own — measurement is what tests whether the intended change is occurring. It should require capacity-based reporting and evidence that the 9% return does not depend on continued refinancing, because a return earned by lending households into distress is not the outcome the mandate describes."
      },
      {
        id: "ibm_case_rural_scale",
        module: 4,
        title: "Sixty towns and capital for four",
        conceptIds: ["ibm_rural_bpo", "ibm_replication", "ibm_labournet"],
        caselet: "A rural services company runs eight centres it owns and staffs directly, employing 640 people in district towns where few graduates migrate for work. Attrition runs at 8% against 45% in comparable city centres, and wage costs are about 40% below metro rates. It holds requests from 60 towns, has ₹4 crore of capital, and needs roughly ₹90 lakh per owned centre. Two pilots run by local entrepreneurs who funded their own fit-out reached break-even in seven months against eleven for owned centres, but one missed the group's training standard and a client audit flagged inconsistent quality across the network; the client's contract specifies a 2% error ceiling. Separately, the company cannot place many capable applicants because they hold no document proving prior work, and client-side supervisors will pay above the local rate only where a skill grade has been independently assessed rather than self-declared.",
        task: "Write the growth plan. The board wants all 60 towns within two years, so be explicit about what is achievable and what has to be true for it to work.",
        rubric: [
          {id: "diagnosis", label: "Governing ideas", description: "Identifies that owned expansion is capital-bound while partner-led replication is not, that common standards are what stop distributed growth from destroying client trust, and that independently assessed skill grades are what convert local capability into higher-paid placement."},
          {id: "evidence", label: "Use of the numbers", description: "Cites specific figures — ₹4 crore against ₹90 lakh per centre, seven months to break-even against eleven, 8% attrition against 45%, the 2% contractual error ceiling, or the audit triggered by one pilot."},
          {id: "integration", label: "How the ideas connect", description: "Connects them: partnering solves the capital and local-knowledge constraint but transfers quality risk to people outside the group's training system, which is precisely what the client contract prices."},
          {id: "decision", label: "The decision", description: "Recommends partner-led growth bound by enforced common standards and certification, states that 60 towns in two years is not fundable through owned centres, and ties expansion to the training and assessment system rather than to site count."},
          {id: "limit", label: "What would change it", description: "Names what must hold for the plan to work — audited standards, error rates inside 2%, assessment capacity keeping pace — or what a further breach would cost in client trust."}
        ],
        exemplar: "Sixty towns in two years is not achievable through owned centres and the arithmetic settles it: ₹4 crore of capital against roughly ₹90 lakh per centre funds four, not sixty. Partner-led replication is the only route that reaches the target, and the pilots suggest it works better on its own terms — local entrepreneurs funding their own fit-out reached break-even in seven months against eleven for owned sites, because they bring both capital and the local hiring knowledge the group does not have. The reason to hesitate is in the same pilots. One missed the training standard and a client audit flagged inconsistent quality across the network, against a contract specifying a 2% error ceiling. That is the real constraint on this plan: distributed growth spreads the brand faster than it spreads the training system, and the client is buying consistency rather than coverage. So the standards have to travel with the partnership and be enforced — certification before a centre takes client work, audited error rates, and the group's right to suspend a site — or the growth that wins towns loses the contract that pays for them. The model's own foundation is worth protecting while this happens. Attrition of 8% against 45% in cities and wage costs 40% below metro rates exist because the work was redesigned around local conditions, not because standards were lowered, and that distinction is what keeps the offer credible to clients. The placement problem points the same way. Capable applicants are turned away for lack of any document proving prior work, while supervisors will pay above the local rate for an independently assessed skill grade. Building assessment and a logged work history is therefore not welfare provision; it is what converts capability the company can already see into placements and higher wages. The plan should be partner-led expansion paced to the rate at which training and assessment can be delivered, not to the number of towns asking."
      },
      {
        id: "ibm_case_energy_offer",
        module: 5,
        title: "A lamp nobody can buy",
        conceptIds: ["ibm_selco", "ibm_bop", "ibm_social_business", "ibm_shared_value"],
        caselet: "A manufacturer has a solar lighting unit that works well and costs ₹9,000 outright. It is being offered in districts where street vendors spend about ₹15 a day on kerosene, roughly ₹450 a month, and where brighter light is estimated to raise daily takings by about ₹90 by extending trading hours. Sales are close to zero. Almost no vendor holds ₹9,000, though a rural bank will finance the unit at ₹10 a day over three years where repayment capacity can be shown. Two earlier solar programmes in these districts collapsed when units failed and no technician was available within 40 km, and vendors now say openly that they will not buy without a repair commitment. The manufacturer's proposed response is a 15% price cut funded from its CSR budget, presented internally as a temporary subsidy until volumes rise.",
        task: "Advise the manufacturer. The CSR-funded price cut is already approved in principle, so say whether it should go ahead and what the alternative is.",
        rubric: [
          {id: "diagnosis", label: "Governing ideas", description: "Identifies that affordability here is a system of product, finance, livelihood benefit and service rather than a price, that the barrier is the payment structure and missing service rather than the headline cost, and that a CSR-funded subsidy is not a model that can sustain itself."},
          {id: "evidence", label: "Use of the numbers", description: "Cites specific figures — ₹15 a day on kerosene against ₹10 a day financed, the ₹90 uplift in takings, ₹9,000 outright, the 40 km with no technician, or the 15% cut against the gap it needs to close."},
          {id: "integration", label: "How the ideas connect", description: "Connects them: the vendor's existing kerosene spend already exceeds the financed repayment, so the offer is affordable once restructured, and the service link is what makes the finance repayable and the earlier programmes' failure relevant."},
          {id: "decision", label: "The decision", description: "Recommends rejecting the CSR-funded price cut in favour of bundling finance and a local service commitment, so the offer covers its own costs at a price the customer can pay."},
          {id: "limit", label: "What would change it", description: "Names what has to hold — service coverage within reach, the bank's willingness to lend, takings uplift materialising — or what the manufacturer gives up by declining the subsidy route."}
        ],
        exemplar: "The price cut should not go ahead, because the product is not failing on price. A vendor already spends about ₹15 a day on kerosene, roughly ₹450 a month, while the bank's terms come to ₹10 a day, and brighter light is expected to add about ₹90 a day in takings by extending trading hours. On those numbers the unit pays for itself from money the vendor is already spending, and adds income on top. What the vendor cannot do is produce ₹9,000 in a single payment. The barrier is the payment structure, not the cost, and a 15% cut leaves a lump sum still far beyond reach while destroying the margin that would fund service. This is the bottom-of-the-pyramid mistake in its usual form: treating a large underserved population as demand, and then discounting when it does not convert, instead of redesigning affordability, access and service around how these households actually receive and spend money. The second barrier is the one the vendors have already named. Two earlier programmes collapsed when units failed with no technician within 40 km, and vendors now say they will not buy without a repair commitment. That is not sentiment; it is a correct assessment of risk. A unit that stops working is a debt with no income behind it, which makes uptime a precondition for the finance rather than an after-sales nicety. Product, finance, livelihood benefit and service form one system here, and removing any link makes the offer unusable regardless of the other three. The recommendation is to bundle the product with the bank's finance and a local service commitment, and to let the offer cover its own costs at a price the customer can pay. A CSR-funded subsidy cannot do that: it makes the offer depend on an annual budget decision rather than on a model that sustains itself, and it will be withdrawn exactly when volumes make it expensive. What must hold is service coverage within reach of these districts and the takings uplift materialising in practice; if the uplift proves smaller, the repayment period is the variable to adjust, not the discount."
      }
    ]
  };

  window.T6_INTEGRATED = SCENARIOS;
}());
