#!/usr/bin/env node

import {createHash} from "node:crypto";
import {mkdir, writeFile} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";

import {createRequire} from "node:module";

import {loadCourses, retrieveEvidence} from "./local-grader.mjs";

const require = createRequire(import.meta.url);
const {loadLectures} = require("./lib/clean_transcripts.js");

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUTPUT = path.join(ROOT, "cloudflare", "src", "generated", "written-bank.mjs");
const EVIDENCE_OUTPUT = path.join(ROOT, "cloudflare", "src", "generated", "written-evidence.mjs");

export function writtenQuestionManifest() {
  const manifest = {};
  for (const [courseId, course] of Object.entries(loadCourses())) {
    for (const question of Object.values(course.questions || {})) {
      if (question.type !== "short-answer" || !Array.isArray(question.rubric) || !question.rubric.length) continue;
      manifest[question.id] = {
        id: question.id,
        courseId,
        conceptId: question.conceptId,
        stem: question.stem,
        caselet: question.caselet || "",
        sourceIds: (question.sourceIds || [question.source]).filter(Boolean),
        rubric: question.rubric.map(({id, label, description}) => ({id, label, description})),
        writtenGaps: (question.writtenGaps || []).map(({id, criterionId, kind, scope, label, repair}) => ({
          id, criterionId, kind, scope, label, repair
        }))
      };
    }
  }
  return manifest;
}

export function serializeWrittenQuestionManifest(manifest = writtenQuestionManifest()) {
  return `/* Generated by tools/build_written_authority_assets.mjs. Do not hand-edit. */\n` +
    `export const WRITTEN_QUESTION_BANK = Object.freeze(${JSON.stringify(manifest, null, 2)});\n`;
}

/* Freeze each question's course evidence at build time.
 *
 * retrieveEvidence never reads the candidate answer - the query is built from the
 * stem, caselet, exemplar and rubric, all of which are fixed. So the evidence for a
 * question is the same for every learner on every attempt, and running a vector
 * search per request recomputes a constant.
 *
 * Freezing it removes the embedding call and the index from the hot path, keeps the
 * course transcripts out of a hosted index entirely, and turns the evidence into
 * something a person can read and correct per question rather than whatever
 * similarity returned that day. Deduplicated it is roughly 50 KiB.
 *
 * The evidence boundary is unchanged: chunks still come only from the lectures the
 * question declares, and a citation is still only valid if it is in this pack. */
export function writtenEvidencePack(sourceRoot = process.env.DUNGEON_TRANSCRIPTS) {
  const lectures = loadLectures(sourceRoot).lectures;
  const pack = {};
  for (const course of Object.values(loadCourses())) {
    for (const question of Object.values(course.questions || {})) {
      if (question.type !== "short-answer" || !Array.isArray(question.rubric) || !question.rubric.length) continue;
      pack[question.id] = retrieveEvidence(question, "", lectures)
        .map(({citation, lectureId, title, text}) => ({citation, lectureId, title, text}));
    }
  }
  return pack;
}

/* Name the pack after its own bytes.
 *
 * DUNGEON_HOSTED_WRITTEN_CORPUS has to match this exactly before hosted marking
 * turns on, so the activation flag cannot drift from the course text the marker
 * will actually quote. Re-freezing the evidence changes the digest and switches
 * hosted marking off until the owner approves the new pack by name. */
export function writtenEvidenceVersion(pack) {
  return `frozen-${createHash("sha256").update(JSON.stringify(pack)).digest("hex").slice(0, 16)}`;
}

export function serializeWrittenEvidencePack(pack) {
  return `/* Generated by tools/build_written_authority_assets.mjs. Do not hand-edit.\n` +
    ` * Frozen course evidence: retrieval never reads the candidate answer, so each\n` +
    ` * question's evidence is a constant and does not need a vector search. */\n` +
    `export const WRITTEN_EVIDENCE_VERSION = ${JSON.stringify(writtenEvidenceVersion(pack))};\n` +
    `export const WRITTEN_EVIDENCE = Object.freeze(${JSON.stringify(pack, null, 1)});\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const manifest = writtenQuestionManifest();
  await mkdir(path.dirname(OUTPUT), {recursive: true});
  await writeFile(OUTPUT, serializeWrittenQuestionManifest(manifest), "utf8");
  console.log(`Prepared ${Object.keys(manifest).length} rubric-marked questions for the hosted authority.`);

  /* Optional: without a transcript source the question manifest still builds, so a
   * checkout without the private lecture pack is not blocked from running gates. */
  const sourceRoot = process.env.DUNGEON_TRANSCRIPTS;
  if (!sourceRoot) {
    console.log("DUNGEON_TRANSCRIPTS is not set; kept the existing frozen evidence pack.");
  } else {
    const pack = writtenEvidencePack(sourceRoot);
    await writeFile(EVIDENCE_OUTPUT, serializeWrittenEvidencePack(pack), "utf8");
    const chunks = Object.values(pack).reduce((total, list) => total + list.length, 0);
    const characters = Object.values(pack).reduce((total, list) => total + list.reduce((n, c) => n + c.text.length, 0), 0);
    console.log(`Froze ${chunks} evidence chunks for ${Object.keys(pack).length} questions (${(characters / 1024).toFixed(0)} KiB of course text).`);
    console.log(`Set DUNGEON_HOSTED_WRITTEN_CORPUS to ${writtenEvidenceVersion(pack)} to activate hosted marking against this pack.`);
  }
}
