#!/usr/bin/env node

import {mkdir, writeFile} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";

import {loadCourses} from "./local-grader.mjs";

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const OUTPUT = path.join(ROOT, "cloudflare", "src", "generated", "written-bank.mjs");

export function writtenQuestionManifest() {
  const manifest = {};
  for (const [courseId, course] of Object.entries(loadCourses())) {
    for (const question of Object.values(course.questions || {})) {
      if (question.type !== "short-answer" || !Array.isArray(question.rubric) || !question.rubric.length) continue;
      manifest[question.id] = {
        id: question.id,
        courseId,
        conceptId: question.conceptId,
        stem: question.stem,
        caselet: question.caselet || "",
        sourceIds: (question.sourceIds || [question.source]).filter(Boolean),
        rubric: question.rubric.map(({id, label, description}) => ({id, label, description})),
        writtenGaps: (question.writtenGaps || []).map(({id, criterionId, kind, scope, label, repair}) => ({
          id, criterionId, kind, scope, label, repair
        }))
      };
    }
  }
  return manifest;
}

export function serializeWrittenQuestionManifest(manifest = writtenQuestionManifest()) {
  return `/* Generated by tools/build_written_authority_assets.mjs. Do not hand-edit. */\n` +
    `export const WRITTEN_QUESTION_BANK = Object.freeze(${JSON.stringify(manifest, null, 2)});\n`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const manifest = writtenQuestionManifest();
  await mkdir(path.dirname(OUTPUT), {recursive: true});
  await writeFile(OUTPUT, serializeWrittenQuestionManifest(manifest), "utf8");
  console.log(`Prepared ${Object.keys(manifest).length} rubric-marked questions for the hosted authority.`);
}
